### ISSUE TITLE
latest chrome store update crashes other extensions and PB crashes itself too

### ISSUE THREAD

**Issue by mailinglists35** [EFForg/privacybadger#1032]

**Comment by Mappa** [comment]
I might have a related problem. It is hard to know when OP doesn't provide any context. 

I'm on Chromium Version 53.0.2785.143

My issue is:
Updated to latest version: 2016.12.7.2
Update blocked because of new requirements, like PB being able to administer downloads and have full control over webpages. 
Could not find a changelog online showing this. 
Activated PB after the update anyways.
Got an warning form chromium saying i have a broken extension, uBlock Origin version: 1.10.0:

WARNING
This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJd2luZG93LkNPTVNDT1JFID0gewoJCXB1cmdlOiBmdW5jdGlvbigpIHsKCQkJX2NvbXNjb3JlID0gW107CgkJfSwKCQliZWFjb246IGZ1bmN0aW9uKCkgewoJCQk7CgkJfQoJfTsKfSkoKTs= because another extension (Privacy Badger) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uICgpIHsKICAgICAgd2luZG93LkNPTVNDT1JFID0gewogICAgICAgIHB1cmdlOiBmdW5jdGlvbigpIHsKICAgICAgICAgIF9jb21zY29yZSA9IFtdOyAvLyBlc2xpbnQtZGlzYWJsZS1saW5lIG5vLXVuZGVmCiAgICAgICAgfSwKICAgICAgICBiZWFjb246IGZ1bmN0aW9uKCkgewogICAgICAgICAgOwogICAgICAgIH0KICAgICAgfTsKICAgIH0pKCk7.

**Comment by truckingsim** [comment]
Same problem as @Mappa 

I'm on Chrome beta: 55.0.2883.75

The warning I got is:

This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CgkvLwoJdmFyIEdhcSA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglHYXEucHJvdG90eXBlLk5hID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5PID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5TYSA9IG5vb3BmbjsKCUdhcS5wcm90b3R5cGUuVGEgPSBub29wZm47CglHYXEucHJvdG90eXBlLlZhID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fY3JlYXRlQXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0QXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5wdXNoID0gZnVuY3Rpb24oYSkgewoJCWlmICggdHlwZW9mIGEgPT09ICdmdW5jdGlvbicgKSB7CgkJCWEoKTsgcmV0dXJuOwoJCX0KCQlpZiAoIEFycmF5LmlzQXJyYXkoYSkgPT09IGZhbHNlICkgewoJCQlyZXR1cm47CgkJfQoJCS8vIGh0dHBzOi8vdHdpdHRlci5jb20vY2F0b3ZpdGNoL3N0YXR1cy83NzY0NDI5MzAzNDUyMTgwNDgKCQkvLyBodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9hbmFseXRpY3MvZGV2Z3VpZGVzL2NvbGxlY3Rpb24vZ2Fqcy9tZXRob2RzL2dhSlNBcGlEb21haW5EaXJlY3RvcnkjX2dhdC5HQV9UcmFja2VyXy5fbGluawoJCWlmICggYVswXSA9PT0gJ19saW5rJyAmJiB0eXBlb2YgYVsxXSA9PT0gJ3N0cmluZycgKSB7CgkJCXdpbmRvdy5sb2NhdGlvbi5hc3NpZ24oYVsxXSk7CgkJfQoJCS8vIGh0dHBzOi8vZ2l0aHViLmNvbS9nb3JoaWxsL3VCbG9jay9pc3N1ZXMvMjE2MgoJCWlmICggYVswXSA9PT0gJ19zZXQnICYmIGFbMV0gPT09ICdoaXRDYWxsYmFjaycgJiYgdHlwZW9mIGFbMl0gPT09ICdmdW5jdGlvbicgKSB7CgkJCWFbMl0oKTsKCQl9Cgl9OwoJLy8KCXZhciB0cmFja2VyID0gKGZ1bmN0aW9uKCkgewoJCXZhciBvdXQgPSB7fTsKCQl2YXIgYXBpID0gWwoJCQknX2FkZElnbm9yZWRPcmdhbmljIF9hZGRJZ25vcmVkUmVmIF9hZGRJdGVtIF9hZGRPcmdhbmljJywKCQkJJ19hZGRUcmFucyBfY2xlYXJJZ25vcmVkT3JnYW5pYyBfY2xlYXJJZ25vcmVkUmVmIF9jbGVhck9yZ2FuaWMnLAoJCQknX2Nvb2tpZVBhdGhDb3B5IF9kZWxldGVDdXN0b21WYXIgX2dldE5hbWUgX3NldEFjY291bnQnLAoJCQknX2dldEFjY291bnQgX2dldENsaWVudEluZm8gX2dldERldGVjdEZsYXNoIF9nZXREZXRlY3RUaXRsZScsCgkJCSdfZ2V0TGlua2VyVXJsIF9nZXRMb2NhbEdpZlBhdGggX2dldFNlcnZpY2VNb2RlIF9nZXRWZXJzaW9uJywKCQkJJ19nZXRWaXNpdG9yQ3VzdG9tVmFyIF9pbml0RGF0YSBfbGluayBfbGlua0J5UG9zdCcsCgkJCSdfc2V0QWxsb3dBbmNob3IgX3NldEFsbG93SGFzaCBfc2V0QWxsb3dMaW5rZXIgX3NldENhbXBDb250ZW50S2V5JywKCQkJJ19zZXRDYW1wTWVkaXVtS2V5IF9zZXRDYW1wTmFtZUtleSBfc2V0Q2FtcE5PS2V5IF9zZXRDYW1wU291cmNlS2V5JywKCQkJJ19zZXRDYW1wVGVybUtleSBfc2V0Q2FtcGFpZ25Db29raWVUaW1lb3V0IF9zZXRDYW1wYWlnblRyYWNrIF9zZXRDbGllbnRJbmZvJywKCQkJJ19zZXRDb29raWVQYXRoIF9zZXRDb29raWVQZXJzaXN0ZW5jZSBfc2V0Q29va2llVGltZW91dCBfc2V0Q3VzdG9tVmFyJywKCQkJJ19zZXREZXRlY3RGbGFzaCBfc2V0RGV0ZWN0VGl0bGUgX3NldERvbWFpbk5hbWUgX3NldExvY2FsR2lmUGF0aCcsCgkJCSdfc2V0TG9jYWxSZW1vdGVTZXJ2ZXJNb2RlIF9zZXRMb2NhbFNlcnZlck1vZGUgX3NldFJlZmVycmVyT3ZlcnJpZGUgX3NldFJlbW90ZVNlcnZlck1vZGUnLAoJCQknX3NldFNhbXBsZVJhdGUgX3NldFNlc3Npb25UaW1lb3V0IF9zZXRTaXRlU3BlZWRTYW1wbGVSYXRlIF9zZXRTZXNzaW9uQ29va2llVGltZW91dCcsCgkJCSdfc2V0VmFyIF9zZXRWaXNpdG9yQ29va2llVGltZW91dCBfdHJhY2tFdmVudCBfdHJhY2tQYWdlTG9hZFRpbWUnLAoJCQknX3RyYWNrUGFnZXZpZXcgX3RyYWNrU29jaWFsIF90cmFja1RpbWluZyBfdHJhY2tUcmFucycsCgkJCSdfdmlzaXRDb2RlJwoJCV0uam9pbignICcpLnNwbGl0KC9ccysvKTsKCQl2YXIgaSA9IGFwaS5sZW5ndGg7CgkJd2hpbGUgKCBpLS0gKSB7CgkJCW91dFthcGlbaV1dID0gbm9vcGZuOwoJCX0KCQlvdXQuX2dldExpbmtlclVybCA9IGZ1bmN0aW9uKGEpIHsKCQkJcmV0dXJuIGE7CgkJfTsKCQlyZXR1cm4gb3V0OwoJfSkoKTsKCS8vCgl2YXIgR2F0ID0gZnVuY3Rpb24oKSB7CgkJOwoJfTsKCUdhdC5wcm90b3R5cGUuX2Fub255bWl6ZUlQID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fY3JlYXRlVHJhY2tlciA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuX2ZvcmNlU1NMID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fZ2V0VHJhY2tlciA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiB0cmFja2VyOwoJfTsKCUdhdC5wcm90b3R5cGUuX2dldFRyYWNrZXJCeU5hbWUgPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gdHJhY2tlcjsKCX07CglHYXQucHJvdG90eXBlLl9nZXRUcmFja2VycyA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuYWEgPSBub29wZm47CglHYXQucHJvdG90eXBlLmFiID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5oYiA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUubGEgPSBub29wZm47CglHYXQucHJvdG90eXBlLm9hID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5wYSA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUudSA9IG5vb3BmbjsKCXZhciBnYXQgPSBuZXcgR2F0KCk7Cgl3aW5kb3cuX2dhdCA9IGdhdDsKCS8vCgl2YXIgZ2FxID0gbmV3IEdhcSgpOwoJKGZ1bmN0aW9uKCkgewoJCXZhciBhYSA9IHdpbmRvdy5fZ2FxIHx8IFtdOwoJCWlmICggQXJyYXkuaXNBcnJheShhYSkgKSB7CgkJCXdoaWxlICggYWFbMF0gKSB7CgkJCQlnYXEucHVzaChhYS5zaGlmdCgpKTsKCQkJfQoJCX0KCX0pKCk7Cgl3aW5kb3cuX2dhcSA9IGdhcS5xZiA9IGdhcTsKfSkoKTs= because another extension (Privacy Badger) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uICgpIHsKICAgICAgdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewogICAgICAgIDsKICAgICAgfTsKICAgICAgLy8KICAgICAgdmFyIEdhcSA9IGZ1bmN0aW9uKCkgewogICAgICAgIDsKICAgICAgfTsKICAgICAgR2FxLnByb3RvdHlwZS5OYSA9IG5vb3BmbjsKICAgICAgR2FxLnByb3RvdHlwZS5PID0gbm9vcGZuOwogICAgICBHYXEucHJvdG90eXBlLlNhID0gbm9vcGZuOwogICAgICBHYXEucHJvdG90eXBlLlRhID0gbm9vcGZuOwogICAgICBHYXEucHJvdG90eXBlLlZhID0gbm9vcGZuOwogICAgICBHYXEucHJvdG90eXBlLl9jcmVhdGVBc3luY1RyYWNrZXIgPSBub29wZm47CiAgICAgIEdhcS5wcm90b3R5cGUuX2dldEFzeW5jVHJhY2tlciA9IG5vb3BmbjsKICAgICAgR2FxLnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwogICAgICBHYXEucHJvdG90eXBlLnB1c2ggPSBmdW5jdGlvbihhKSB7CiAgICAgICAgaWYgKCB0eXBlb2YgYSA9PT0gJ2Z1bmN0aW9uJyApIHsKICAgICAgICAgIGEoKTsgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBpZiAoIEFycmF5LmlzQXJyYXkoYSkgPT09IGZhbHNlICkgewogICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICAvLyBodHRwczovL3R3aXR0ZXIuY29tL2NhdG92aXRjaC9zdGF0dXMvNzc2NDQyOTMwMzQ1MjE4MDQ4CiAgICAgICAgLy8gaHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vYW5hbHl0aWNzL2Rldmd1aWRlcy9jb2xsZWN0aW9uL2dhanMvbWV0aG9kcy9nYUpTQXBpRG9tYWluRGlyZWN0b3J5I19nYXQuR0FfVHJhY2tlcl8uX2xpbmsKICAgICAgICBpZiAoIGFbMF0gPT09ICdfbGluaycgJiYgdHlwZW9mIGFbMV0gPT09ICdzdHJpbmcnICkgewogICAgICAgICAgd2luZG93LmxvY2F0aW9uLmFzc2lnbihhWzFdKTsKICAgICAgICB9CiAgICAgIH07CiAgICAgIC8vCiAgICAgIHZhciB0cmFja2VyID0gKGZ1bmN0aW9uKCkgewogICAgICAgIHZhciBvdXQgPSB7fTsKICAgICAgICB2YXIgYXBpID0gWwogICAgICAgICAgJ19hZGRJZ25vcmVkT3JnYW5pYyBfYWRkSWdub3JlZFJlZiBfYWRkSXRlbSBfYWRkT3JnYW5pYycsCiAgICAgICAgICAnX2FkZFRyYW5zIF9jbGVhcklnbm9yZWRPcmdhbmljIF9jbGVhcklnbm9yZWRSZWYgX2NsZWFyT3JnYW5pYycsCiAgICAgICAgICAnX2Nvb2tpZVBhdGhDb3B5IF9kZWxldGVDdXN0b21WYXIgX2dldE5hbWUgX3NldEFjY291bnQnLAogICAgICAgICAgJ19nZXRBY2NvdW50IF9nZXRDbGllbnRJbmZvIF9nZXREZXRlY3RGbGFzaCBfZ2V0RGV0ZWN0VGl0bGUnLAogICAgICAgICAgJ19nZXRMaW5rZXJVcmwgX2dldExvY2FsR2lmUGF0aCBfZ2V0U2VydmljZU1vZGUgX2dldFZlcnNpb24nLAogICAgICAgICAgJ19nZXRWaXNpdG9yQ3VzdG9tVmFyIF9pbml0RGF0YSBfbGluayBfbGlua0J5UG9zdCcsCiAgICAgICAgICAnX3NldEFsbG93QW5jaG9yIF9zZXRBbGxvd0hhc2ggX3NldEFsbG93TGlua2VyIF9zZXRDYW1wQ29udGVudEtleScsCiAgICAgICAgICAnX3NldENhbXBNZWRpdW1LZXkgX3NldENhbXBOYW1lS2V5IF9zZXRDYW1wTk9LZXkgX3NldENhbXBTb3VyY2VLZXknLAogICAgICAgICAgJ19zZXRDYW1wVGVybUtleSBfc2V0Q2FtcGFpZ25Db29raWVUaW1lb3V0IF9zZXRDYW1wYWlnblRyYWNrIF9zZXRDbGllbnRJbmZvJywKICAgICAgICAgICdfc2V0Q29va2llUGF0aCBfc2V0Q29va2llUGVyc2lzdGVuY2UgX3NldENvb2tpZVRpbWVvdXQgX3NldEN1c3RvbVZhcicsCiAgICAgICAgICAnX3NldERldGVjdEZsYXNoIF9zZXREZXRlY3RUaXRsZSBfc2V0RG9tYWluTmFtZSBfc2V0TG9jYWxHaWZQYXRoJywKICAgICAgICAgICdfc2V0TG9jYWxSZW1vdGVTZXJ2ZXJNb2RlIF9zZXRMb2NhbFNlcnZlck1vZGUgX3NldFJlZmVycmVyT3ZlcnJpZGUgX3NldFJlbW90ZVNlcnZlck1vZGUnLAogICAgICAgICAgJ19zZXRTYW1wbGVSYXRlIF9zZXRTZXNzaW9uVGltZW91dCBfc2V0U2l0ZVNwZWVkU2FtcGxlUmF0ZSBfc2V0U2Vzc2lvbkNvb2tpZVRpbWVvdXQnLAogICAgICAgICAgJ19zZXRWYXIgX3NldFZpc2l0b3JDb29raWVUaW1lb3V0IF90cmFja0V2ZW50IF90cmFja1BhZ2VMb2FkVGltZScsCiAgICAgICAgICAnX3RyYWNrUGFnZXZpZXcgX3RyYWNrU29jaWFsIF90cmFja1RpbWluZyBfdHJhY2tUcmFucycsCiAgICAgICAgICAnX3Zpc2l0Q29kZScKICAgICAgICBdLmpvaW4oJyAnKS5zcGxpdCgvXHMrLyk7CiAgICAgICAgdmFyIGkgPSBhcGkubGVuZ3RoOwogICAgICAgIHdoaWxlICggaS0tICkgewogICAgICAgICAgb3V0W2FwaVtpXV0gPSBub29wZm47CiAgICAgICAgfQogICAgICAgIG91dC5fZ2V0TGlua2VyVXJsID0gZnVuY3Rpb24oYSkgewogICAgICAgICAgcmV0dXJuIGE7CiAgICAgICAgfTsKICAgICAgICByZXR1cm4gb3V0OwogICAgICB9KSgpOwogICAgICAvLwogICAgICB2YXIgR2F0ID0gZnVuY3Rpb24oKSB7CiAgICAgICAgOwogICAgICB9OwogICAgICBHYXQucHJvdG90eXBlLl9hbm9ueW1pemVJUCA9IG5vb3BmbjsKICAgICAgR2F0LnByb3RvdHlwZS5fY3JlYXRlVHJhY2tlciA9IG5vb3BmbjsKICAgICAgR2F0LnByb3RvdHlwZS5fZm9yY2VTU0wgPSBub29wZm47CiAgICAgIEdhdC5wcm90b3R5cGUuX2dldFBsdWdpbiA9IG5vb3BmbjsKICAgICAgR2F0LnByb3RvdHlwZS5fZ2V0VHJhY2tlciA9IGZ1bmN0aW9uKCkgewogICAgICAgIHJldHVybiB0cmFja2VyOwogICAgICB9OwogICAgICBHYXQucHJvdG90eXBlLl9nZXRUcmFja2VyQnlOYW1lID0gZnVuY3Rpb24oKSB7CiAgICAgICAgcmV0dXJuIHRyYWNrZXI7CiAgICAgIH07CiAgICAgIEdhdC5wcm90b3R5cGUuX2dldFRyYWNrZXJzID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLmFhID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLmFiID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLmhiID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLmxhID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLm9hID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLnBhID0gbm9vcGZuOwogICAgICBHYXQucHJvdG90eXBlLnUgPSBub29wZm47CiAgICAgIHZhciBnYXQgPSBuZXcgR2F0KCk7CiAgICAgIHdpbmRvdy5fZ2F0ID0gZ2F0OwogICAgICAvLwogICAgICB2YXIgZ2FxID0gbmV3IEdhcSgpOwogICAgICAoZnVuY3Rpb24oKSB7CiAgICAgICAgdmFyIGFhID0gd2luZG93Ll9nYXEgfHwgW107CiAgICAgICAgaWYgKCBBcnJheS5pc0FycmF5KGFhKSApIHsKICAgICAgICAgIHdoaWxlICggYWFbMF0gKSB7CiAgICAgICAgICAgIGdhcS5wdXNoKGFhLnNoaWZ0KCkpOwogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfSkoKTsKICAgICAgd2luZG93Ll9nYXEgPSBnYXEucWYgPSBnYXE7CiAgICB9KSgpOw==.

**Comment by cooperq** [comment]
@Mappa good point I have added a changelog to the chrome web store! 

This problem is because ublock and privacy badger are both replacing tracking scripts now and due to the way that chrome is written only one of them can do the redirect so the other one gets this warning. Not really sure we can do much about this.

**Comment by cooperq** [comment]
@mailinglists35 can you please provide more detail about the issue you are seeing?

**Comment by truckingsim** [comment]
@cooperq I get you put a wontfix label on this, but are you just going to say you can't use ublock and privacy badger at the same time?  I imagine MANY people do this.  It feels wrong to add a new feature that just breaks an extensions that a lot of people want to use with privacy badger.  Is there really nothing we can do except decide whether we want privacy badger or ublock?

**Comment by cooperq** [comment]
@truckingsim you can use them both at the same time! In this case they are both trying to do the same thing but only one of them can do it. And then thanks to bad chrome UI you get a warning. But the effect is still the same.

**Comment by ghostwords** [comment]
Hello! Actually, there is no real issue here, nothing is broken, it's just a pointless warning that Chrome needlessly bugs extension users with. However given that this is an annoyance to users, Privacy Badger should try to avoid this warning as much as possible. In this case, PB's redirect scripts are based on uBlock's in the first place, so we might as well tweak them to match uBlock's exactly to avoid the perceived conflict with uBlock.

**Comment by Mappa** [comment]
@ghostwords Yes, uBlock does not crash or cripple the browser, so the re-naming of the title is appropriate. It is what chromium says it is - a warning. 

I did not know it was based off of uBlock. I will try just disabling uBlock for some time and see if PB can fill in the shoes, so to speak.

**Comment by ghostwords** [comment]
@Mappa No need to disable uBlock. Again, there is no real problem using both.

**Comment by Mappa** [comment]
@ghostwords Okay, thanks. Anyway, if one suffice, why have two :)

@cooperq Thanks for the changelog and permission requirements description. Always appreciate when software is upfront about such things.

**Comment by mailinglists35** [comment]
> can you please provide more detail about the issue you are seeing?

@cooperq 
step1 update PB from chrome store
step2 receive chrome popup about PB has crashed AND about crashing other extensions
step 3 disable PB
step 4 all other extensions work ok after disabling the updated PB

**Comment by mailinglists35** [comment]
i didn't get warnings. i got crash of pb and this crash triggered crash of other extensions

**Comment by mailinglists35** [comment]
updated to latest release, still crashes on load

**Comment by mailinglists35** [comment]
![image](https://cloud.githubusercontent.com/assets/2054302/21136716/c62e5778-c137-11e6-974a-f18d7f9c3e2e.png)

**Comment by mailinglists35** [comment]
the second i loaded the extension from folder

**Comment by mailinglists35** [comment]
please reopen and change back the title, my issue is about PB crashing other extensions and itself, not about warnings

**Comment by ghostwords** [comment]
Hi @mailinglists35, you should open a new issue as this one is about something else, as you pointed out.

**Comment by mailinglists35** [comment]
@ghostwords i filed this issue with title "latest chrome store update crashes other extensions and PB crashes itself too". i didn't have the screenshot at hand (which i've later posted in comment https://github.com/EFForg/privacybadger/issues/1032#issuecomment-266702254

then @Mappa hijacked the issue with a totally different behaviour ("This extension failed to redirect a network request" message), then you confirmed the hijacking by retitling the issue.

I expected @Mappa to be suggested to file a separate issue, not me!

**Comment by ghostwords** [comment]
It seems that the thread did get repurposed, it's true. But now that it happened, and there is all this valid discussion about something else, doesn't it make sense to start fresh with your issue? Feel free to keep going here of course, just trying to help.

**Comment by mailinglists35** [comment]
@ghostwords could you point to the correct issue reporting that PB is **crashing** and that **is determining other extensions to crash**, like I've shown in https://github.com/EFForg/privacybadger/issues/1032#issuecomment-266702254 above? thanks.

**Comment by cooperq** [comment]
Fine. reopining this issue. @mailinglists35 what version of chrome are you running, what operating system? Can you open the privayc badger debug console (by clicking enable developer mode on the chrome extensions page and then clicing inspect background page underneath privacy badger) are there any errors displaying there?

**Comment by mailinglists35** [comment]
@cooperq meanwhile I have updated to chrome store version Updated: December 15, 2016, and it no longer crashes. Thank you! :)

**Comment by mailinglists35** [comment]
this the only warning

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
getFileContents @ socialwidgetloader.js:80

using srware iron by the way :)
