### ISSUE TITLE
firefox lockup after update.

### ISSUE THREAD

**Issue by PeterSteinberg** [EFForg/privacybadger#1049]
I just updated to the latest version (2016.12.8.1) and it locks up Firefox (51.0b6 32-bit) on Windows 7.

**Comment by cooperq** [comment]
Do you see any messages in the browser console before it locks up? What
happens when you restart firefox?

**Comment by PeterSteinberg** [comment]
No, it just went to “installing the update” and froze completely at the end.

Killed the firefox process and restarted it and firefox was hung during startup before displaying anything on the screen.

After a couple of minutes I killed the processes again, restarted in safe mode, disabled the privacybadger plugin and restarted and everything was fine.

Reverted back to  1.9.2 and everything works as expected.

**Comment by groovecoder** [comment]
FWIW, a fresh install of PB 2016.12.8 on Firefox 51.0b6 (64-bit) on Mac OS X 10.11.6 works for me. I'll see if I can get access to a Windows 7 machine at the office tomorrow.

**Comment by modestindustries** [comment]
Saw the same issue, Firefox 50.0.2 on Mac OS X 10.11.6, PB 2016.12.8. Removed the add-on, restarted FF, reinstalled PB 2016.12.8 and it seems to be stable. Symptoms include stalling, pinned CPU, inability to reach any websites.

**Comment by AaronLasseigne** [comment]
I had the exact same setup as @modestindustries and re-installing also fixed it for me.

For anyone experiencing this on OS X you can try:
1.  hold option and launch Firefox
2. select safe mode
3. open your add-ons
4. remove PB
5. quit and launch FF normally
6. install PB

**Comment by davidsm** [comment]
I had the same issue on Ubuntu 14.04, Firefox 51.1.0.

Reinstalling Privacy Badger sort of solved it for me as well. 

I say sort of, because while it's not stalling Firefox anymore, it's allowing everything instead, including domains it has identified as tracking me, which kind of makes it a bit useless.

**Comment by groovecoder** [comment]
Since those reporting are updating, I wonder if this only affects users with a large `LEGACY` object that has to be migrated into the WebExtensions storage?

**Comment by cooperq** [comment]
Yea that is kinda what im thinking too.  I'll try to do some tests today and see if I can't make it smoother.  
@davidsm an unfortunate side effect of uninstalling privacy badger is that this deletes all the data. So privacy badger forgets what was tracking you and has to re-learn.  

On December 13, 2016 11:51:51 AM PST, luke crouch <notifications@github.com> wrote:
>Since those reporting are updating, I wonder if this only affects users
>with a large `LEGACY` object that has to be migrated into the
>WebExtensions storage?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/privacybadger/issues/1049#issuecomment-266842928

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ricardograca** [comment]
I'm also seeing this issue. Does it mean that there is some kind of data update going on behind the scenes and I should just let it finish?

**Comment by mikelabonte** [comment]
I'm getting these console warnings running in Firefox 50.0.2 on Windows 8.1:

1481667111400   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Loading extension 'jid1-MnnxcxisBPnSXQ-eff@jetpack': Reading manifest: Error processing permissions.9: Unknown permission "privacy"
1481667111403   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Loading extension 'jid1-MnnxcxisBPnSXQ-eff@jetpack': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1481667111403   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Loading extension 'jid1-MnnxcxisBPnSXQ-eff@jetpack': Reading manifest: Error processing minimum_chrome_version: An unexpected property was found in the WebExtension manifest.
1481667111403   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Loading extension 'jid1-MnnxcxisBPnSXQ-eff@jetpack': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1481667111404   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Loading extension 'jid1-MnnxcxisBPnSXQ-eff@jetpack': Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.
1481667111630   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Please specify whether you want browser_style or not in your browser_action options.

With Privacy Badger enabled Firefox uses a lot of CPU and memory, then the event queue stalls. It works normally with PB disabled. Apparently Firefox got updated Dec 8, PB Dec 13.

**Comment by watchmoretv** [comment]
Same here as mikelabonte as mikelabonte on Ubuntu:
console gives me

1481677426671	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing permissions.9: Unknown permission "privacy"
1481677426674	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1481677426674	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing minimum_chrome_version: An unexpected property was found in the WebExtension manifest.
1481677426674	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1481677426675	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.
1481677426733	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.


After deleting, reinstall failed due to permission issues.

**Comment by pjlsergeant** [comment]
I believe I have the same issue. I have recorded a PCAP session from it - it appears to be connecting to > 1,000 sites and sending what look like certificate requests. I'd be happy to email this file to someone who'd know what to do with it.

Most worrying is that it seems to ... know which sites I've visited? For example, one of the sites it requests from is: https://www.karstenaichholz.com/

I have my history to auto-clear on exit, and I haven't been there for a while, but as it's a personal blog site, it seems unlikely it'd be on any internal PB list. What's going on there? What information exactly is being retained?

**Comment by alexristich** [comment]
@pjlsergeant Regarding the domains that are being stored, these are stored in order to allow Privacy Badger determine whether a tracker is present on multiple distinct domains. I'm not sure exactly why it's sending out requests to all these sites (or if it even is - @cooperq should have a better idea here), but the recent update to Privacy Badger includes a migration to a new WebExtensions version, which requires that all this data be put in a well-defined place from the old extension and loaded into the new extension.

These domains are retained on your local device while Privacy Badger remains installed; note that for all pages visited on a given domain, only the top level domain will be stored.

**Comment by pjlsergeant** [comment]
@alexristich That's a pretty big break in expectations. I absolutely do not expect a privacy tool to be maintaining a plain-text copy of every domain it's seen me visit, and I wonder if other users do? Couldn't these be -- at the very least -- `scrypt`d?

Regarding "or if it even is", I don't think my network monitor is deceiving me, but I'd be happy to send the capture to someone.

**Comment by groovecoder** [comment]
I'd be interested to take a look.

**Comment by groovecoder** [comment]
I'm at lcrouch at mozilla dot com.

**Comment by ghostwords** [comment]
Browser lockups should be fixed by (some combination of) #1082, #1145 and #1182.
