### ISSUE TITLE
PB does not seem to be blocking any domains in Ubuntu Linux

### ISSUE THREAD

**Issue by darren12345** [EFForg/privacybadger#1072]
PB 2016.12.8.1
Ubuntu 16.04
FF 50.1.0

Reproduced on two different machines. Visiting sites that definitely have trackers (according to PB on Windows 7) displays a 0 on the tool bar icon. If I open the PB window, it does list potential trackers but they are all defaulted to allow.

Updated to Add: Just tested on a clean FF profile. Same result.

**Comment by darren12345** [comment]
OK, after reading around I understand it might take a while for PB to start detecting and blocking trackers, especially with 3rd party cookies blocked like I have. So put this one on hold for a moment...

**Comment by alexristich** [comment]
That was my first thought as well. When it's first installed, Privacy Badger doesn't block anything - it'll start blocking as it builds up a local database of which sites are tracking you and will then determine the appropriate action.

An import/export feature was recently added to the Options page to allow you to transfer your user data from one device to another, though in order to take advantage of it you need to visit a few sites first so Privacy Badger can start learning which sites are trackers.

Third party cookies are the most prevalent method of tracking, so if you have these disabled then it will take noticeably longer for trackers to be detected, as it will only learn of new ones that use other tracking methods. For now I'll go ahead and close this issue, though if you notice any issues please post again and I'd be happy to reopen it and take a closer look.
