### ISSUE TITLE
Automatically Block Potential Trackers

### ISSUE THREAD

**Issue by rdetert** [EFForg/privacybadger#1090]
There are too many trackers to keep up with. It seems that some are even using rotating through random domain names. It would be nice to be able to automatically block potential trackers.

**Comment by Calefornia** [comment]
Managing block lists hasn't been the goal of this project, and it seems redundant when other great tools exist (uBlock Origin or uMatrix). And because new, random domains won't be included in current lists, we need something else. It might be nice though, since we have the import/export options now. That provides a pretty good shield instead of leaving new browsers to figure it out, but it still doesn't address random domains.

I believe NoScript has a very strict option where anything outside of the parent site can be blocked, but there's no learning model. It involves lots of pain and configuration to make sites work at the minimum level while blocking extra fluff.

PB could fill this gap by learning which kinds of domains are likely to be trackers. This should avoid a giant list, and then settings could be changed after PB makes assumptions, just like the sliders currently allow. The PB heuristic strategy could assess the probability of a domain being unwanted. Some domains are gibberish and include random numbers or the word "ad," but I'm not sure what algorithms or regex filters are best suited to identifying suspicious domains.

Who knows, maybe we can all upload our .json files and let a machine learning system figure it out...

Here are some bad domains from my .json file:
ad.adlegend.com
ad.doubleclick.net
ad2.cdns.turn.com
beacon.squixa.net
dis.criteo.com

**Comment by cooperq** [comment]
um, privacy badger already does automatically block domains which have the potential to be trackers based on their behavior such as setting cookies or super cookies or certain forms of fingerprinting. So, problem solved! Just sit back and let privacy badger scan for you!

**Comment by rdetert** [comment]
Maybe I just have no idea how to use Privacy Badger ;) It detects the trackers but all the switches are flipped to green, which I assumed meant they were being allowed to process. I have been manually training it to block the domains or cookies via red / yellow switches. My original question was just meant to flip everything to red, blacklisting it, and then re-enabling them to unbreak sites I visit frequently.

**Comment by cooperq** [comment]
https://www.eff.org/privacybadger#faq-How-does-Privacy-Badger-work?

Hmm interesting feature idea but I'm hesitant to implement such an option because I think it would be used by a small number of people and I would llke to avoid feature creep. Thanks though!
