### ISSUE TITLE
Bandsintown can't connect with Facebook

### ISSUE THREAD

**Issue by loekiedepo** [EFForg/privacybadger#1104]
First let me say I love the addon (using on Firefox on a couple of different PCs).

I'm an artist and use [Bands in Town](https://news.bandsintown.com/home) quite a lot. Recently, I haven't been able to add new shows via Facebook though.
As it turns out, it's Privacy Badger that is actively blocking the connecting javascript from Facebook to BiT (or maybe the other way around, either way I can't do anything with BiT on my computers).

You can read a little about how BiT works via Facebook [here](http://www.artists.bandsintown.com/). Basically, you add shows via a plugin on your Facebook profile and BiT adds those shows to their database. You can then include widgets and javascript on all of your web pages that reads out of their database. So you add shows in 1 place and you can display them all over the web in the same format.
As said, the problem is that you can't add shows via Facebook anymore, because Privacy Badger is actively blocking them. Would be nice if Bands in Town could be white- or yellowlisted.

**Comment by alexristich** [comment]
Thanks for the report! This one looks to be a bit tricky. I haven't looked into the specifics of how the plugin works, but it's possible that yellow-listing it _might not_ fix it due to cookies being stripped out from the requests. In general the (yellow) cookieblock list works best for CDNs (content delivery networks) which don't require cookies or authentication to serve content. 

For unique cases like this, the best approach here is to add the domain to the whitelist. You can do this by going to the Options page (click the gear icon in the Privacy Badger popup) then going to the "Whitelisted domains" tab. I'd recommend inputting `*.bandsintown.com` just to make sure you cover all their subdomains!

I'll go ahead and close this issue for now, though if you run into any other issues with this or have other comments do feel free to follow up.

**Comment by loekiedepo** [comment]
Thanks for the quick reply, adding to whitelist does help. Maybe it's an option to do this out of the box? Had some issues with viewing BiT widgets on my website because of privacy badger too.
