### ISSUE TITLE
"Pin to Overflow Menu" / "Move to Menu" breaks popup layout in Firefox

### ISSUE THREAD

**Issue by stephenyeargin** [EFForg/privacybadger#1120]
## Steps to Reproduce

1. Install Privacy Badger on a machine running macOS and Firefox 50+
1. Right click on the Privacy Badger icon in the toolbar and select "Move to Menu"
1. Open the menu and click the Privacy Badger icon
1. Observe a broken layout for the controls

## Expected Behavior

- Layout should adjust to fill given space that is roughly 40 pixels narrower than what is allocated

## Screenshots

![screen shot 2017-01-04 at 11 55 19 am](https://cloud.githubusercontent.com/assets/80459/21652993/b1d0dfd2-d274-11e6-988e-ac2c04b60de1.png)

![screen shot 2017-01-04 at 11 53 51 am](https://cloud.githubusercontent.com/assets/80459/21653000/b72999c4-d274-11e6-9e76-e8f3c1f4587d.png)

![screen shot 2017-01-04 at 11 53 37 am](https://cloud.githubusercontent.com/assets/80459/21653004/b81c8558-d274-11e6-8cfd-c80522864129.png)

**Comment by cooperq** [comment]
I think that @groovecoder was maybe trying to fix this issue. Luke, did you come up with anything?

**Comment by cooperq** [comment]
@groovecoder I just looked it up and it should have been in the last release @stephenyeargin what version of privacy badger do you have?

**Comment by stephenyeargin** [comment]
@cooperq `2016.12.15.1`, installed via the site on January 4.

**Comment by cooperq** [comment]
Yep that's the latest version. @groovecoder I guess we should check on your fix, hopefully it didn't get reverted somehow.

**Comment by groovecoder** [comment]
Hmm ... looks like my fix was specific to the #instruction element. I'll send another PR that makes it work for the whole body element.

**Comment by cooperq** [comment]
This is still an issue. The previous fix was reverted as it broke other things.

**Comment by berkes** [comment]
Title mentions [Firefox 50 for Mac]. 
Problem occurs on Firefox 54.0 on Ubuntu Linux too.

**Comment by lemnis** [comment]
I was testing something within FF 57 and remembered this issue.

From Firefox 57 onward, the layout is changed. The popup would now look like:

![image](https://user-images.githubusercontent.com/3999815/30512652-7fea531a-9af4-11e7-9882-888679686c49.png)

I did earlier some messy tests to fix the width issues with `display: grid`, because this issue also messes up the extension within android. The code can be found at: https://github.com/lemnis/privacybadger/tree/fix-popup-layout

The current result of my code:

![image](https://user-images.githubusercontent.com/3999815/30512723-ba95671a-9af5-11e7-99c8-e5565029592d.png)

**Comment by bcyphers** [comment]
@generalbrus Thanks! I think this is a good issue, unless @ghostwords has plans to work on it already.

**Comment by ghostwords** [comment]
This is a great issue to help us with.

I hope we can discover a few clever CSS tweaks to get the popup usable in the overflow menu (as opposed to make large structural changes to the popup).
