### ISSUE TITLE
V 2017.1.26.1 in Firefox 51.0.1 throws error

### ISSUE THREAD

**Issue by otheraquanaut** [EFForg/privacybadger#1210]
Hi,
When I open a tab in Firefox I get the error: `The procedure entry point PK11_PubDerive could not be located in the dynamic link library nss3.dll`. I get this error in Windows 7 and 10. I have tried removing all add-ons and plugins. It is only adding or removing Privacy Badger that affects this error.

Anyone have a solution for this? I've tried different copies of nss3.dll to no avail.

Regards,
[file redacted]
Brian

**Comment by cowlicks** [comment]
@otheraquanaut I extracted this from your file.
![image1](https://cloud.githubusercontent.com/assets/598099/23037296/b2c8ac16-f43a-11e6-89d1-827c87e6858f.png). 

You may want to remove that file, it contains someones full name (B... K....) and company (Z.. I.. C.. ltd). 

Otherwise, I'm not sure what issue is here.

**Comment by ghostwords** [comment]
Typing up the error for searchability: "The procedure entry point PK11_PubDerive could not be located in the dynamic link library nss3.dll."

Searching brings up other Firefox users with this issue, but no solution ([for example](https://support.mozilla.org/t5/Firefox/The-procedure-entry-point-PK11-PubDerive-could-not-be-located-in/td-p/1158594)).

**Comment by ghostwords** [comment]
Is this still an issue using the latest stable Firefox (55)?

**Comment by cowlicks** [comment]
Firefox 51.0.1 is no longer supported, so I think we can close this. Please re-open, or open another issue if it is still a problem
