### ISSUE TITLE
Compatibility with W3C Tracking Preference Expression specification

### ISSUE THREAD

**Issue by alanton** [EFForg/privacybadger#1230]
The W3C has been working on a technical specification for the DNT signal and resulting interaction between user agents and publishers. This document has not been adopted as a standard but is in an advanced state and can be read [here](https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html). 

Many elements of the TPE are addressed in other ways in Privacy Badger, but by extending compatibility with the TPE we expand and simplify the universe of DNT implementation, which is a good thing.

To this end we want to initially add support for two features of the TPE:

1. In the W3C specification sites are required to post a [Tracking Status Resource (TSR)](https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#status-resource), setting out the general tracking policy of the site in machine readable form at /.well-known/dnt/

TSRs should contain a tracking value and a compliance array. The former describes the site's tracking practices, the latter specifies the regulatory regime with which the site complies (EFF DNT, General Data Protection Regulation etc). 

PB already checks .well-known/dnt-policy.txt and should also look for the url for a TSR to verify if the site supports the EFF's DNT policy.

2. In response to a valid DNT request for a specific resource the TPE requires a response (designated as a _Tk response header field_ ) containing a [Tracking Status Value (TSV)](https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#tracking-status-value).

One of the possible TSV responses is 'C', which means that the user is being tracked with their consent. Under the EFF's DNT policy a site can obtain user consent to tracking by acquiring a transparent and unambiguous opt-in. Where consent has been given the Tk header/TSV 'C' can be used to store and signify such consent in the user interface. 

Currently PB will unblock third parties to sites which have posted the policy (such as Medium.com). Alternately users can 'opt-in' by whitelisting a site or toggle the slider for a given domain to green. Introducing support for the consent signal will be a step towards giving users easier control over these decisions.

This is a lot of work and issues to be clarified but there is strong interest in this from the W3C and from our partner @michael-oneill at Baycloud.

**Comment by ghostwords** [comment]
Here is my latest understanding of what we should aim for in Privacy Badger.

A big part of what W3C is working on seems like a standardization of Click-to-Play/[widget substitution](https://github.com/EFForg/privacybadger/blob/master/doc/DESIGN-AND-ROADMAP.md#widget-substitution) functionality.

Instead of the privacy browser (extension) being wholly responsible for detecting where a third-party-service-powered comments widget (for example) lives, figuring out what set of resources are required for it to function, and showing an appropriate in-page message with a set of controls for allowing the comments widget to appear, the responsibility becomes shared between the widget's host site and the browser.

A site might receive the DNT: 1 header, check for the presence of this consent API (how?), and instead of loading the comments widget, show an in-place message with a set of controls for allowing the widget.   If an allow button is clicked, the browser will be notified via this JavaScript consent API (how?). (If there are multiple privacy extensions, they should all be notified.) The browser can then take appropriate action: unblock the specified domains (for the specified site (for the specified duration)). This might necessitate a page reload; the better user experience would be to load a set of specified resources dynamically without reloading the page.

@alanton @michael-oneill How does the above sound? I know there is also the TSR JSON, but I am not yet sure how it integrates into typical Privacy Badger user workflows. Showing a new icon for participating domains in the browser popup doesn't seem so compelling.

**Comment by michael-oneill** [comment]
The TSR needs to exist otherwise the storeSiteSpecificTrackingException should be ignored. The TSR should also identify the data controller (the company or whatever responsible for the resource), in the "controller" property. PrivacyBadger can also check to see if a reference to the EFF DNT policy is in the "compliance" array.

There is other information that may be useful, for example the "same-party" array that identifies the other subresource domains that are managed by the site, i.e. they have the same Data Controller. There will be other properties that we have an issue open (in the TPWG) to discuss.

The DNT:0 is a signal to say the user has given explicit consent to that domain, either across the whole web ("Web-Wide" Consent) or simply as a subresource to that particular site ("Site-Specific" consent). It can either be set by the site (using the API), or within the browser/extension with its own UI. As I said I do not think web-wide consent will be very useful because few will want to agree to it.

IMO PB should unblock (as if the user had returned the slider to green) a domain where DNT is 0, because this should only be the result of explicit user consent, "freely given, specific, informed & unambiguous" as required by European law. Bouncer has an option to get it to confirm with the user (with a dialog UI) when the store*TrackingException API is called, I will put a link in the library so you can intercept that if you want.

If the user returns the slider to red then you can assume that is a client-side revoke, and call the remove*TrackingException API. The resource server will then see DNT:1 again. If there is no current DNT "Exception" the remove is ignored anyway.

Here are the links I promised.

A potted guide to implementing DNT (needs updating)
https://trackingprotection.github.io/Implementation/DNTGuide/

A page that demonstrates the API
https://baycloud.com/dntapi

a page that exercises the API
https://baycloud.com/api/test

**Comment by ghostwords** [comment]
>One of the possible TSV responses is 'C', which means that the user is being tracked with their consent. Under the EFF's DNT policy a site can obtain user consent to tracking by acquiring a transparent and unambiguous opt-in. Where consent has been given the Tk header/TSV 'C' can be used to store and signify such consent in the user interface.

We could start by using different messaging (icon + tooltip text) in the popup for domains that respond with a tracking status value (TSV) of "C". We may need to tweak our caching logic for DNT checking (currently avoid rechecking for up to a week since the most recent check) to support this effectively.

For example, a user logging into Medium would result in Privacy Badger reporting something about having consented to tracking for the relevant Medium domains, instead of those domains "promising not to track you".

**Comment by ghostwords** [comment]
@alanton @andresbase Yes, I think we might instead work on making it easier for services to be compliant with our DNT policy (especially in light of the GDPR).
