### ISSUE TITLE
Privacy Badger spawning DNS queries when opening browser

### ISSUE THREAD

**Issue by danjor404** [EFForg/privacybadger#1323]
OS:  Ubuntu 16.04.02 64-bit
Browser: Chrome 57.0.2987.133 (64-bit)
Plugin: 2017.3.28

Over the past week I've been getting notifications on my firewall of outbound traffic destined for countries I've blocked based on their MaxMind geo location (Russia, China, spammy reputation IPs, etc).  Strangely enough it was only happening when I first opened a new process of Chrome.  After some packet capture and testing I was able to determine that it only happens when Privacy Badger was enabled.  It is spawning DNS queries followed a small amount of HTTPS traffic to the corresponding IP address (I believe it's pulling dnt-policy.txt files but I didn't setup an SSL MIM to confirm).  Each of the names being queried can be found in the "User Filter Settings" list.

Nothing is checked under my Privacy settings in Chrome except "Send a "Do Not Track" request with your browsing traffic" and it only opens a New Tab when launching chrome.  In tests without Privacy Badger enable the only Chome generated traffic should be accounts.google.com.

I didn't find it appropriate to post under these other threads because OS version/details differed but might be the same issue,..
Privacy badger calling /.well-known/dnt-policy on sites not currently visited in Firefox #1303
Malware sites trigger alerts in Chrome days later #1321

And a shout out and thank you to the developers.  I really do appreciate the work you guys and EFF does.  -Danjor

**Comment by ghostwords** [comment]
Hi Danjor,

I think what you are seeing is Privacy Badger issuing checks for the [EFF Do Not Track policy](https://www.eff.org/dnt-policy) for domains you ran into while browsing at some point in the past. The reason you haven't noticed these checks earlier is that periodic (as opposed to as-you-surf) rechecking was broken until Badger version 2017.3.28.

Since that update, we've gotten feedback about CPU issues caused by DNT policy rechecking. We reviewed our approach, and decided we are going to remove periodic rechecking in the next update. So you won't be seeing these anymore once #1312 is released (should be this or the following week).
