### ISSUE TITLE
provide a list of known trackers

### ISSUE THREAD

**Issue by mrphs** [EFForg/privacybadger#1333]
There are some sites that we know for sure 100% are always tracking users. I think privacy badger should be shipped with a list of these trackers. or if you don't want to make it the default (which I think should be, anyways)... having a button in the settings where I can download and import known trackers would be dope!

**Comment by GeorgeWL** [comment]
I know we don't want to be overly similar to Adblock or uBlock, but there's a particularly good part which I do feel would fill in this problem.

![screenshot-www nationalcrimeagency gov uk 2017-06-22 13-33-02](https://user-images.githubusercontent.com/5931248/27856238-636ed80a-6165-11e7-8b56-5a9e4bdb2eff.png)

**Comment by cowlicks** [comment]
Please use ublock origin. Privacy Badger differentiates itself by using heuristics instead of whitelists and blacklists.

The reason we want to avoid lists is because access to the list becomes increasingly valuable as the number of users grow. This creates a conflict of interest between us and our users.

Also, as you can see, there are other extensions that already do this very well.

I think the actionable items here are:
* do a better job explaining our philosophy of why we don't want lists
* recommend using ublock origin in conjunction with PB

I'd like to close this as 'wontfix' and create a seperate issue with the two items above, but I'll cc @ghostwords for a 2nd opinion

**Comment by cowlicks** [comment]
These probably be good to have in the FAQ. This is related to emphasizing why badger doesn't block stuff immediately, issue #1374

**Comment by ghostwords** [comment]
I started a more technically-oriented FAQ on the wiki: https://github.com/EFForg/privacybadger/wiki.

**Comment by ghostwords** [comment]
While we shouldn't ever get in the business of compiling lists of things for Badger to block, I think there is space for us to provide some sort of community learning feature down the road. People could opt-in to share their Badger's learning, which would then get auto-aggregated and loaded by new Badgers. I guess let's close this one in lieu of #1299.
