### ISSUE TITLE
Add option to allow learning in Incognito/Private Browsing modes

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#1367]
My apologies if this is the way Privacy Badger is supposed to work, or this functionality is not possible to add, but I noticed that Privacy Badger does not add rules when I am in incognito mode.

These are the steps I performed to test this.

1. Deleted user data directory so Privacy Badger is in its default state of not blocking anything.
2. Visited nytimes.com and wsj.com in incognito mode - no rule changes were made.
3. Visited the same sites in regular mode - Privacy Badger added rules to block several domains.

Browser: Google Chrome 58.0.3029.96
OS: Ubuntu 16.04

**Comment by ghostwords** [comment]
Correct, Privacy Badger does not learn anything while in Incognito/Private Browsing modes. This is done on purpose for privacy reasons, respecting the intention of Incognito mode browsing.

**Comment by ghostwords** [comment]
Let us know if you have any suggestions for how Badger should handle this better.

**Comment by Stephen-X** [comment]
Perhaps Privacy Badger can have an option that asks for permission to block in incognito mode (disabled by default of course)? It makes sense to not allow Privacy Badger to block anything in incognito mode, as it will leave traces of visiting history in tracking domains, but I'm sure there're people like me who use incognito mode simply to avoid leaving too many temp files on disk or showing top sites visited in Chrome's new tab page. Besides, since incognito mode only provides a somewhat "fake" sense of privacy, I think it may be better off to add an optional tracking protection functionality to it, like Firefox did.

**Comment by ghostwords** [comment]
Privacy Badger does block in Incognito / Private Browsing modes, it's just that Privacy Badger won't learn about new trackers from Incognito browsing.

This is done in order to avoid recording any data in Incognito browsing (and having that information get mixed with data recorded during regular browsing). This data includes which external domains were seen tracking on which site domains.

**Comment by Stephen-X** [comment]
@ghostwords I made a mistake in my last post. Yes I know Privacy Badger is able to block in incognito mode, but since Privacy Badger doesn't ship with a basic list, it's still not very useful; what I meant by "blocking" is actually "learning new trackers". As I mentioned previously, I understand that allowing Privacy Badger to learn in incognito mode potentially leaves traces locally, which is an undesirable behavior for most extensions. However, I think it will be great for Privacy Badger to have this **optional** exception for its specific use case.

Incognito mode itself only provides a very limited guarantee of privacy: although it doesn't remember user history locally, others who are very eager to learn about your activities can always learn from your ISP etc. It will be silly for anyone to use incognito mode to avoid exposing user history in public computers, and people should definitely go for Tor Browser or Tails if they want real sense of privacy. Therefore, **"avoid being tracked" is actually more valuable for incognito mode users on their personal computers**. Firefox understood this and did a good job including Disconnect in its Private Browsing mode, but for obvious reasons any such lists will not be comprehensive and stay up-to-date all the time (not to mention Chrome will never have such functionality out of the box), and that's where heuristic-based tracker filters like Privacy Badger really shine. I think it will be more valuable for incognito mode users who don't mind having their visited tracker history recorded locally on their personal computers to have a fully functional tracker blocker that stays up-to-date by itself (as stated above, Privacy Badger is not very helpful if you use incognito mode most of the time). Of course such option should be disabled by default, and warning about potential info leakage should be provided when users try to enable it in settings, but it will still be a nice choice to keep around.

**Comment by ghostwords** [comment]
Got it, thanks! I'll update this issue to a feature request then.

**Comment by ghostwords** [comment]
We could add a preference (for example, c8018fbef5bf495bc1289e6192625a918e7c622a) and then check the preference inside `tabIsIncognito()`. Then, [the places that check `tabIsIncognito()`](https://github.com/EFForg/privacybadger/search?utf8=✓&q=tabIsIncognito&type=) will automatically do the right thing on Incognito/Private Browsing tabs when the preference is enabled.

**Comment by ghostwords** [comment]
Note that we now plan on shipping with a pre-trained database (#1891).
