### ISSUE TITLE
Unittests errors in console

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1395]
When running unittests I see this in my console:
```
chrome-extension://mekoeccjihallkjjjkcfpogljdnekmkd/tests/icons/badger-19.png:1 GET chrome-extension://mekoeccjihallkjjjkcfpogljdnekmkd/tests/icons/badger-19.png net::ERR_FILE_NOT_FOUND
chrome-extension://mekoeccjihallkjjjkcfpogljdnekmkd/tests/icons/badger-38.png:1 GET chrome-extension://mekoeccjihallkjjjkcfpogljdnekmkd/tests/icons/badger-38.png net::ERR_FILE_NOT_FOUND
index.html:1 Could not load action icon 'icons/badger-19.png'.
index.html:1 Could not load action icon 'icons/badger-38.png'.
```

**Comment by ghostwords** [comment]
This is because [src/js/background.js references icons files using relative paths](https://github.com/EFForg/privacybadger/blob/ea19a6d38a97bf3609bc45eb293fe0ca341109fd/src/js/background.js#L703), which doesn't work when `src/js/background.js` is sourced by [src/tests/index.html](https://github.com/EFForg/privacybadger/blob/ea19a6d38a97bf3609bc45eb293fe0ca341109fd/src/tests/index.html).

While this should be easy to fix (by switching to absolute paths with `chrome.extension.getURL`?), I think it's a symptom of some larger problems. We run Privacy Badger twice when the tests page is open. Listeners are registered twice, background page timers that have no business running alongside tests do run, your local settings can interfere with tests, tests can overwrite your local settings, ...

**Comment by ghostwords** [comment]
We could get around this by switching our unit testing setup to use mock WebExtensions APIs, which would also pave the way for [code coverage](1169).

**Comment by ghostwords** [comment]
Added some workarounds in #1400 that should take care of local settings interfering with tests, and tests being able to overwrite your local settings.
