### ISSUE TITLE
PB Icon Does Not Display on FF 29.0 Mac

### ISSUE THREAD

**Issue by jk5312** [EFForg/privacybadger#148]
I gather that there is supposed to be a Privacy Badger icon display on the toolbar, and this icon can be used to modify the PB settings. It does not display on FireFox 29.0 on Mac Mt. Lion.

It is my understanding that the PB code is based on ABP. I have ABP installed -- is that any issue?

Other Add-On installed include:
NoScript
Disconnect
DuckDuckGo Plus
Google Analytics Opt-Out
Google Privacy
Google no-tracking-url
Hide Toolbar with One Tab
HTTPS Everywhere
QuickJS
RefControl
TabsOnBottom
UserAgentSwitcher
Poster
Download Helper

Thanks in advance!

JK

**Comment by LinuxOnTheDesktop** [comment]
I have the same problem, with the current release version of the AddOn, on Windows. And the problem has occurred before - [as this bug report shows](https://github.com/EFForg/privacybadgerfirefox-legacy/issues/316).

**Comment by ghostwords** [comment]
Hi @LinuxOnTheDesktop, could you open a new issue? Is Privacy Badger listed on `about:addons`? What happens if you try to open Privacy Badger's options page? Are there any errors in Privacy Badger's [background page console](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain#2-open-privacy-badgers-extension-background-page)? Does uninstalling and then reinstalling Privacy Badger resolve the issue?

It sounds like something went wrong with your Firefox profile, and it may have to be ["refreshed"](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings), but I can't say for sure without learning more about your problem.

**Comment by LinuxOnTheDesktop** [comment]
@ghostwords

Thanks.

I have opened a new issue as #2625.
