### ISSUE TITLE
demandware.edgesuite.net breaks layout

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1504]
http://www.newbalance.com/

`demandware.edgesuite.net` breaks layout.

No snitch map.

`cdn.cquotient.com` is also blocked (don't see any immediate side effects), but aren't CDNs not supposed to be blocked?

**Comment by ghostwords** [comment]
This should have been fixed by #1428, released as part of 2017.6.13.1 ... Seems related to https://github.com/EFForg/privacybadger/issues/1127#issuecomment-310255351.

Is there no snitch map because the [migration](https://github.com/EFForg/privacybadger/pull/1428/files#diff-bb2fc8d5922b62bea41c295ebab401a6) in #1428 removed it? Why is `edgesuite.net` still blocked then? Could you post your action map for it?

Do you have any cookies or other local storage from `cdn.cquotient.com`?

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/29471918-dde89f12-841f-11e7-8371-c6cf1cfc0463.png)
![image](https://user-images.githubusercontent.com/12802056/29471941-ed745764-841f-11e7-9325-cd54b25685c2.png)
![image](https://user-images.githubusercontent.com/12802056/29471963-0ffd3f80-8420-11e7-9ae5-d017f022d5a0.png)
![image](https://user-images.githubusercontent.com/12802056/29472023-50518294-8420-11e7-87ae-157666f6d1c1.png)

**Comment by terrorist96** [comment]
Seems to be fixed for me now.
