### ISSUE TITLE
Error with SessionBox

### ISSUE THREAD

**Issue by yoav-epstein** [EFForg/privacybadger#1518]
This is what I see in chrome://extensions/

Warning:
This extension failed to modify the request header "Cookie" of a network request because the modification conflicted with another extension (SessionBox - Free multi login to any website).

**Comment by cowlicks** [comment]
@ghostwords can you link the duplicate issue? I didn't see one any others with sessionbox.

**Comment by ghostwords** [comment]
@cowlicks I was in the middle of writing my comment; this is a cosmetic Chrome error, not specific to any one extension in particular. I don't think we have a definitive ticket to point to though.

**Comment by ghostwords** [comment]
Hi @yoav-epstein, are you experiencing any actual issues outside of the warning message? If not, this is just a common cosmetic issue in Chrome, a case of bad browser UI. You shouldn't keep seeing it past the first time.

**Comment by yoav-epstein** [comment]
@ghostwords Thanks for looking at my request.  I believe the extension is working correctly (as far as I know). I noticed the warning and thought you should know.

**Comment by ghostwords** [comment]
No problem! Does this answer on our wiki FAQ make sense? https://github.com/EFForg/privacybadger/wiki#why-am-i-getting-a-this-extension-failed-to-redirect-a-network-request-to--warning-in-chrome. Let me know if we should tweak it.

**Comment by yoav-epstein** [comment]
@ghostwords thanks for the clarification in the FAQ.  When you write "only the more recently installed extension will succeed", to me, it implies that the modifications done by the first extension failed, or were overwritten.  If both changes were applied, then it would clearer to write "chrome highlights when two or more extensions modify the same content"

**Comment by ghostwords** [comment]
Privacy Badger tries to remove cookies from request and from response headers for certain ("[yellowlisted](https://github.com/EFForg/privacybadger/blob/master/doc/yellowlist-criteria.md)") domains. It looks like SessionBox also does something to cookie headers, at least sometimes on some websites.

I think what happens is what the warning says, Privacy Badger didn't get to modify headers because SessionBox modified the same headers in a different way. So only the more recently installed extension's changes succeeded. This should be fine though ... SessionBox gets to work how it should, although Privacy Badger doesn't get to remove cookies sometimes. We might want to look more into this at some point.

**Comment by yoav-epstein** [comment]
Good explanation.  Thank You.

**Comment by ghostwords** [comment]
Duplicate of #1134.
