### ISSUE TITLE
Disabled privacy badger prevents refresh on ebay search listings (and some other sites)

### ISSUE THREAD

**Issue by naught101** [EFForg/privacybadger#1530]
Ebay.com.au search listings don't update when options on the left (e.g. location, sub-categories, auction format) are clicked. The URL does update, so the listing can be updated with F5. This is with privacy badger **disabled for the site**. 

I used "Extension Conflict Troubleshooter" for firefox was to bisect search (against one of the core core firefox extensions unlikely to have an actual conflict) to confirm that this only occurs when Privacy Badger is enabled as an extension (but "disabled for this site" on Ebay).

All ebay related domains that I can see are yellow-listed. The issue also occurs when privacy badger is enabled for ebay.

Other updating listings on some other sites are also similarly affected (I think Goodreads search listings is another palce I've noticed it.

The bug is quite annoying. Please let me know if I can provide any more information.

**Comment by cowlicks** [comment]
What version of Firefox are you using? I'm unable to reproduce this with Firefox 54 on Linux.

**Comment by naught101** [comment]
Same, 54 on KDE Neon (*buntu 16.04). I guess it's possible that it's a clash with another plugin...

**Comment by naught101** [comment]
Same, 54 on KDE Neon (*buntu 16.04). I just tried the bisection search again with privacy badger as the centre of the clash search, and it didn't find anything, do it's not a clash. I will try uninstalling it and reinstalling it - does that clear the privacy badger related data?

**Comment by naught101** [comment]
Tried reinstalling privacy badger. Same behaviour.

**Comment by ghostwords** [comment]
This seems like a duplicate of #1438, which is caused by a Firefox bug with the following Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1373776.

 Could you double-check that you run into the same bug by (temporarily) disabling all other add-ons (including Privacy Badger), installing [this test add-on](https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip) I made, and verifying that the problem occurs with the add-on and goes away without it?

To load the above add-on in Firefox, unzip the archive somewhere, visit about:debugging, click on Load Temporary Add-on, and pick the manifest.json file inside the unzipped folder.

**Comment by naught101** [comment]
Yep, this is a duplicate. That test addon causes the same problem.

**Comment by ghostwords** [comment]
Thanks for checking!

**Comment by ghostwords** [comment]
According to https://github.com/EFForg/privacybadger/issues/1295#issuecomment-315998618, you should be able to get rid of this issue in your Firefox profile without having to start over from scratch by [refreshing your Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and then reinstalling all your add-ons.

**Comment by ghostwords** [comment]
This might be fixed now that Firefox 55 reached stable.
