### ISSUE TITLE
Privacy Badger Breaks tripadvisor.co.uk

### ISSUE THREAD

**Issue by shadyeglenn** [EFForg/privacybadger#1560]
When Privacy Badger is enabled, all Trip Advisor pages show up as left justified text with broken image links.  If I disable Privacy Badger in Chrome, Trip Advisor loads fine (testing primarily on tripadvisor.co.uk).  I tried whitelisting Trip Advisor and sliding all of the domains to the green section to allow all Trip Advisor sites, but the issue still shows up.

**Comment by ghostwords** [comment]
Do you have any other privacy/ad blocking extensions, or does this happen exclusively with Privacy Badger?

**Comment by ghostwords** [comment]
Does Privacy Badger report `static.tacdn.com` as blocked on TripAdvisor pages, by any chance?

**Comment by ghostwords** [comment]
Looks like `tripadvisor.com` and `tacdn.com` are already associated together by Privacy Badger. The problem is that none of the regional TripAdvisor domains are there. Here are three example pages that make Privacy Badger start blocking TripAdvisor resources:

- https://www.tripadvisor.pt/ShowUserReviews-g196602-d1553899-r179531414-Cap_d_Agde_Naturist_Village-Cap_d_Agde_Agde_Herault_Occitanie.html
- https://www.tripadvisor.nl/Attraction_Review-g293917-d1021770-Reviews-Flight_of_the_Gibbon-Chiang_Mai.html
- https://www.tripadvisor.es/Restaurant_Review-g189403-d12367729-Reviews-Che_Cocina_Y_Barra_Sudamericana-Piraeus_Piraeus_Region_Attica.html

The quick fix would be to add all their regional URLs to their MDFP entry. We get lots of error reports for TripAdvisor. The proper fix might be to implement #1253.

**Comment by shadyeglenn** [comment]
Yep, Privacy Badger reports static.tacdn.com as blocked on TripAdvisor pages.  I can workaround the issue by switching static.tacdn.com from block domain to block cookies, and after doing so TripAdvisor loads fine.  Thanks!

**Comment by cowlicks** [comment]
I'm working on this, it should close #1253 as well
