### ISSUE TITLE
MDFP mozilla.org & firefox.com possibly not equivalent

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1572]
https://github.com/bitwarden/core/issues/38

I realize I submitted a bunch of equivalent domains found by looking at LastPass' list, however, I don't know if they have all been verified to the criteria you specify as equivalent in regards to Privacy Badger logic.

Has the list been reviewed to see if all actually match what PB should consider equivalent?

**Comment by cowlicks** [comment]
@jawz101 do you have a link to the lastpass list?

LastPas probably has a much stricter definition of MDFP, since messing up might mean leaking your credentials.

For us, MDFP means domains that are loading resources from each other, and also are organizationally tied so that they likely already have access to your identifying information.

I realize these have different credentials, but I don't think they get much value in tracking you across these.

**Comment by ghostwords** [comment]
Here is the original Privacy Badger issue: #1052.

**Comment by ghostwords** [comment]
Yeah, this is fine. Unless we find any domains not owned by the same parent organization, there is no issue.

**Comment by ghostwords** [comment]
The idea behind multi-domain first parties being that Privacy Badger doesn't (at the moment) care about first-party (same-domain) tracking, only third-party (cross-domain) tracking, and there is no automatic way for Badger to know that `mozilla.org` and `firefox.com` belong to the same entity. For our purposes, actually, these domains might be unnecessary (are there any "tracking" resources loaded by one on another?), but that's not a big issue.
