### ISSUE TITLE
use.fontawesome.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1601]
http://jobs.thermofisher.com/

`use.fontawesome.com` breaks "images" of arrows.

![image](https://user-images.githubusercontent.com/12802056/29686946-c0d051f4-88e8-11e7-8a38-d735ded7a302.png)

**Comment by ghostwords** [comment]
What about just for "fontawesome"?

**Comment by terrorist96** [comment]
My bad
![image](https://user-images.githubusercontent.com/12802056/29687197-833b3b64-88e9-11e7-82c7-55a32261875c.png)

**Comment by terrorist96** [comment]
https://www.budsgunshop.com/catalog/product_info.php/products_id/84723

Rating stars blocked

**Comment by triskweline** [comment]
Hi, I had to investigate a bug today where a Privacy Badger users can't seem to load icons from `use.fontawesome.com`. Is this intended behavior? It's a very popular icon font.

**Comment by ghostwords** [comment]
I don't think this is intended behavior, as I am still unable to reproduce tracking from any `fontawesome.com` domains. I do see a couple of user error reports a month that block `use.fontawesome.com`.

I'll make Privacy Badger users forget about this domain in the next update. Let's see if this issue comes back then.

**Comment by triskweline** [comment]
Thank you for looking into this @ghostwords .

**Comment by triskweline** [comment]
Thanks :+1:
