### ISSUE TITLE
Webpack transition

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#1612]
What do you think of replacing the current pseudo-module loader system with Webpack? The first step would be to convert the current code to valid CommonJS. CommonJS will be replaced by ES6 modules later.

**Comment by ghostwords** [comment]
Pros:
- Is the more "correct" approach to breaking up the codebase. Current solution may confuse contributors into thinking Privacy Badger has a real module loader, but since it does not, could lead to code issues such as module loading order-related errors (A depends on B but accidentally required before B).
- Having a build process paves the way for using things like React.
- Is something a contributor is excited about.

Cons:
- Not clear this solves any (user or developer) pain points. Any module loading order issues are easily fixed by hand. I also don't recall seeing any such issues.
- Having a build process increases development process complexity.

Let me know what you think of this provisional list. My feeling is that you being excited to work on this is the biggest reason for doing it. I would like to avoid introducing a build process for as long as we can help it, and I would like to focus on fixing user-impacting issues.

**Comment by koops76** [comment]
@ghostwords It saves developers the pain of having to work around the current setup, to start.

**Comment by koops76** [comment]
@ghostwords "Having a build process increases development process complexity."

Wrong, it decreases it.

**Comment by ghostwords** [comment]
It would be helpful if you laid out your views in more detail, by providing examples of current pain points, for example. It's not so productive to say your conversation partner is wrong without explaining why.

**Comment by koops76** [comment]
@ghostwords "My feeling is that you being excited to work on this is the biggest reason for doing it."
Strongly disagree. It would make both my workflow and others' simpler, but I don't think that my "excitement" has clouded my judgement.

**Comment by koops76** [comment]
@ghostwords One of major reasons: https://webpack.js.org/concepts/hot-module-replacement/.

**Comment by ghostwords** [comment]
How would Hot Module Replacement work with an extension/add-on where you have to (generally, outside of certain browser popup/options page scenarios) reload the extension in the browser before the browser recognizes your changes?

**Comment by koops76** [comment]
@ghostwords If I am correct, it fetches the changes live from a local web server.

**Comment by ghostwords** [comment]
You should try setting up a simple proof-of-concept. I am not sure how you would get around needing to click "Reload" on `chrome://extensions/` (in Chrome, with something similar in Firefox).

**Comment by koops76** [comment]
@ghostwords https://github.com/salsita/chrome-extension-skeleton

It doesn't have HMR but nevertheless I recommend you to read through the code.

It also shows how Webpack may handle packing an extension into a CRX file using a third-party plugin.

**Comment by koops76** [comment]
@ghostwords I will extend it to have HMR in a short time.

**Comment by ghostwords** [comment]
Closing for now.
