### ISSUE TITLE
Privacy Badger prompts for permissions to twitter.com after upgrade to Firefox 55

### ISSUE THREAD

**Issue by StevenShockley** [EFForg/privacybadger#1619]
After upgrading to Firefox 55, I get prompted to allow Privacy Badger to access twitter.com.  I'll attach a screen shot.  I don't use Twitter; do you know why it would need this access?  It appears the upgrade for Privacy Badger fails when I deny access.  Thanks.

**Comment by StevenShockley** [comment]
![privacybadger](https://user-images.githubusercontent.com/19954947/29877358-63663e78-8d6d-11e7-910d-fca5593238e3.png)

**Comment by ghostwords** [comment]
Do you know what your previous Firefox version was? What is your current Privacy Badger version (the one that is being upgraded)?

**Comment by ghostwords** [comment]
My first thought is this is some kind of Firefox WebExtensions permissions checking bug.

Privacy Badger always asked for complete access on all websites, which is required to do Privacy Badger's job of detecting tracking and cancelling requests to tracking domains.

We did add a couple of `twitter.com`-specific content scripts with Privacy Badger version 2017.6.13, but they shouldn't trigger the new permissions dialog as Privacy Badger always had access to `twitter.com` ...

**Comment by ghostwords** [comment]
I'm going to close this for now; let me know if you have any more information.

**Comment by gthb** [comment]
I got this just now after installing Firefox Quantum (hadn't used Firefox for some months so I can't say which upgrade might have triggered this, and don't know what my previously installed version was). Privacy Badger version is 2017.4.19.1, last updated May 2, 2017.

**Comment by ghostwords** [comment]
This seems like a Firefox permissions bug.

Firefox clearly shouldn't ask for added permissions for a single site (`twitter.com`) if the add-on already has permissions for all sites.

This particular case seems to happen in Firefox when you somehow still have a Badger older than 2017.6.13 (where we [added the `twitter.com` permission](https://github.com/EFForg/privacybadger/commit/77d53c7b9d89e1ad0ae915c79318437714735c70#diff-051a8a7bcae8db1e4cee8eb09b52e619)). This doesn't seem worth tracking down in this case, but can bite us again in the future, if we ever add more site-specific content scripts) and this bug isn't fixed by Firefox.

**Comment by ghostwords** [comment]
We should look into whether there is already a [Mozilla Bugzilla](https://bugzilla.mozilla.org) bug filed for this, and if there isn't one, file one ourselves.

**Comment by clizzin** [comment]
I just experienced this permissions request. Running Firefox 57.0.03 on macOS and Privacy Badger 2017.1.26.1. Unfortunately, I'm not aware when the most recent upgrade of either Firefox or Privacy Badger itself occurred. I don't _think_ an upgrade occurred because I had the browser open for more than 24 hours prior to seeing the permissions request prompt.

<img width="468" alt="screen shot 2018-01-01 at 12 12 25 pm" src="https://user-images.githubusercontent.com/55812/34470752-549f5b22-eeed-11e7-867e-bd5741e13176.png">

**Comment by ghostwords** [comment]
This may be fixed as of Firefox 58 (https://bugzilla.mozilla.org/show_bug.cgi?id=1331769); we should confirm.

**Comment by StevenShockley** [comment]
I can't seem to duplicate it now.  Thanks!

**Comment by bcyphers** [comment]
Can we close this?

**Comment by StevenShockley** [comment]
I think so, I haven't seen this message for quite some time.  Thanks!

**Comment by fjl82** [comment]
I got this same popup today, but this time about facebook.com. I don't use facebook, and never want to use it, so questions like this makes me wonder what PB is doing that it would need this permission...

I read something in the comments above about site-specific scripts. That would make sense (since FB is one of the biggest privacy invaders out there), but the popup made me question if PB was sending data to FB behind my back. I assume it's safe to update? My version is currently 2018.4.23.

**Comment by ghostwords** [comment]
Hi @fjl82, which version of Firefox do you have? You seem to be running into a Firefox bug that was fixed in Firefox 58 and later.

Privacy Badger needs to access your browsing data in order to do its job: figure out who trackers are and then stop them. The Firefox bug has to do with Firefox needlessly asking for permission to access browsing data on domains the add-on already has access to. We released [Facebook-specific privacy protections last week](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking); older versions of Firefox get confused and pop the permissions dialog. There is no actual problem here, just an old Firefox bug.

Let me know if this makes sense or not.

**Comment by ghostwords** [comment]
Phew, you had me worried for a second. Thanks for following up!
