### ISSUE TITLE
Change text of the Tweet on the firstRun page

### ISSUE THREAD

**Issue by lenazun** [EFForg/privacybadger#1620]
https://github.com/EFForg/privacybadger/blob/a1bc52444843a6a00c0c57d8b138b4ee2c891ef0/src/skin/firstRun.html#L68

From Soraya:

I just met with a-team, and we wanted to request a few changes to the default tweet that comes from installing Privacy Badger.

The original:

"I just installed Privacy Badger, a new tool from EFF to stop companies from spying on your browsing habits - https://eff.org/privacybadger"

Change to:

"I just installed Privacy Badger, a new tool from @EFF to stop companies from spying on your browsing habits https://eff.org/privacybadger"
(add the @ before EFF, remove the hyphen)

Rainey asks:

After people tweet, is there a way to have a "suggested" account which prompts them to follow EFF?

**Comment by andresbase** [comment]
@lenazun "Twitter may suggest accounts to follow after the author has successfully posted a Tweet. These displayed accounts are influenced by the via and related web intent parameters." 

We can add via @eff but then we have @eff twice, also since the EFF is already mentioned it would probably be suggesting the follow anyway. I haven't been able to replicate the suggestion with "via". What have you seen in other cases?

**Comment by andresbase** [comment]
Per our discussion we'll add "&related=eff" to the url.

**Comment by lenazun** [comment]
Thank y'all
