### ISSUE TITLE
Add uBlock Origin to the FAQ

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1638]
Recommended in a support email.

Add [here](https://www.eff.org/privacybadger#faq-How-is-Privacy-Badger-different-from-Disconnect,-Adblock-Plus,-Ghostery,-and-other-blocking-extensions?).

**Comment by davidhedlund** [comment]
For two reasons:
1) uBlock Origin is the second most popular add-on on addons.mozilla.org.
2) uBlock Origin is a WebExtension.

**Comment by gorhill** [comment]
I fail to see how uBlock Origin matches any of the rationale detailed in there:

> could function well without any settings, knowledge, or configuration by the user

uBO's out of the box settings are pro-users, its default settings are that of an install-and-forget blocker for non-tech-savvy users.

> produced by an organization that is unambiguously working for its users rather than for advertisers

uBO is completely pro-users, never compromised for advertisers (not that it was tried), quite the opposite. Yes, I am not an "organization", but that should be irrelevant, the track record speaks for itself.

> In our testing, all of them required some custom configuration to block non-consensual trackers

Turns out uBO has been picked as performing best with regard to trackers by [Stiftung Warentest](https://www.test.de/Tracking-Wie-unser-Surfverhalten-ueberwacht-wird-und-was-dagegen-hilft-5221609-0/) -- including against Privacy Badger: surely the opinion of a pro-consumers organization must be worth _something_, if only to not be strung together with ABP, Ghostery et al.

> Several of these extensions have business models that we weren't entirely comfortable with

There is no business model behind uBO.

**Comment by ghostwords** [comment]
Hi @gorhill! I agree; while uBlock Origin is indeed very popular, it is also in a class of its own. We shouldn't just add it to that paragraph and call it a day.

There are good reasons for both Privacy Badger and uBlock Origin to exist; I routinely recommend uBlock Origin to Privacy Badger users. It's not at all clear what updates we should make to Privacy Badger's homepage though.

**Comment by gorhill** [comment]
@ghostwords Thanks for the support.

I am just baffled by the suggestion of uBO being lumped with those other blockers (hence my reaction here) as if the [substance and driving principles](https://github.com/gorhill/uBlock#philosophy) of the project are completely unimportant.

**Comment by alanton** [comment]
@gorhill! 

There is no question that we would lump you in with AdBlock Plus et al. Everyone at EFF holds you and uBO in the highest regard, and we know that it is a project that serves _users_ not private commercial purposes. 

I think  @cowlicks was just indicating that we should add something about uBO to the FAQ because we regularly get asked about other extensions, possible conflicts etc., so any reference to uBO will be as a recommendation not a warning.

**Comment by cladmi** [comment]
I ended up here because of the same concern. I am a long time uBlock origin user (using advanced settings), learned about Privacy Badger and was wondering if it would make sense to use both or use PB in replacement of uBO.

The FAQ only mention the other extensions and never uBlock Origin. So I agree that it will not go into the same section, but a reference would be appreciated there.
I was expecting to showing me what PB could give me different.
Its hard to do fair comparative description but if @gorhill is included in the discussion, it should be possible to get something nice.

Maybe the issue title is misleading in that case and I could migrate to another issue or if @cowlicks you are on the same page and want to change the title.

**Comment by ghostwords** [comment]
The closest answer we have is currently on this repository's wiki under ["Is Privacy Badger compatible with other privacy extensions and/or ad blockers?"](https://github.com/EFForg/privacybadger/wiki#is-privacy-badger-compatible-with-other-privacy-extensions-andor-ad-blockers). I plan on moving the answers on the wiki to the [website](https://www.eff.org/privacybadger).

**Comment by ghostwords** [comment]
Perhaps something like the following?

>uBlock Origin is an excellent privacy tool. uBlock Origin and Privacy Badger should work well together.
>
>uBlock Origin protects using lists, while Privacy Badger protects by automatically learning about trackers as you browse, which means Privacy Badger might catch things that uBlock Origin doesn't know about.
>
>Privacy Badger will learn about far fewer trackers when used together with uBlock Origin, but that's  OK.

**Comment by davidhedlund** [comment]
@ghostwords Go for it.

**Comment by cladmi** [comment]
@ghostwords Thank you for the links.
Your proposition looks good to me.

**Comment by ghostwords** [comment]
Documented as part of [https://www.eff.org/privacybadger#faq-Is-Privacy-Badger-compatible-with-other-extensions,-including-other-adblockers?](https://www.eff.org/privacybadger#faq-Is-Privacy-Badger-compatible-with-other-extensions,-including-other-adblockers?).
