### ISSUE TITLE
Better explain what makes Privacy Badger different on homepage and add-on listing pages

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1675]
New Privacy Badger users seem to run into a few common points of frustration:
- Why isn't Privacy Badger blocking anything yet? (#1374)
- Why isn't Privacy Badger blocking first-party ads? ([Privacy Badger is a non-consensual tracking blocker, not an ad blocker.](https://www.eff.org/privacybadger#faq-Why-doesn't-Privacy-Badger-block-all-ads?))
- Why isn't it easier to manually block all domains in Privacy Badger? (Privacy Badger is supposed to be as much hands-off as possible; you shouldn't have to interfere unless something is broken.)

We should consider updating the language we use when describing Privacy Badger on its homepage and its add-on listing pages to help reduce user frustration.

Following up on #1603.

**Comment by andresbase** [comment]
From our latest conversations.

We want to modify the layout of the page to waste less space and make it clear our three main points already mentioned here which are:

* [ ] Why is Privacy Badger different?
* [ ] Why nothing is blocked when installed?
* [ ] How does it work?

There are other things we should do to improve the messaging. Like the text which introduces/explains Privacy Badger:

* [ ] Simplify FAQ and make it easier to link and read.
* [ ] Make it easier to translate and switch languages.

**Comment by ghostwords** [comment]
Updated the README in #2017.

Used the new text as base to update Firefox and Chrome extension listing descriptions (Opera listing to be updated later, at release time).

Still need to update the homepage.

**Comment by ghostwords** [comment]
@DJCrashdummy Let me know if you have any feedback regarding the latest description updates.

**Comment by DJCrashdummy** [comment]
the readme seems good to me: it is short, not to techy and at least broaches all important points. :+1: 

btw: the only extension-provider, which seems updated for now is firefox! - you have mentioned opera, but also [chrome](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) still has the old description.

---
i'm still not 100% sure about the short slogan used at [firefox addons](https://addons.mozilla.org/firefox/addon/privacy-badger17/) (as already stated in https://github.com/EFForg/privacybadger/issues/1603#issuecomment-329459204 at the second bigger section): _Protects your privacy by blocking spying ads and invisible trackers._
don't get me wrong, with the new description it shouldn't really be a problem... as long as everything is read. :wink:

i'm not sure if it is somehow an "official" slogan, since a derivation of it is also used at the homepage, but something completely different at github.
just brought it up again since you are already at the wording, so a few thoughts about this may also be worth it. ...and probably harmonize them.

**Comment by ghostwords** [comment]
OK, thank you! Agreed, the tagline should get updated and standardized across all locations (homepage, GitHub, extension stores, extension description).

**Comment by ghostwords** [comment]
Taglines:

place | text
--- | ---
Homepage | Privacy Badger blocks spying ads and invisible trackers.
GitHub | Privacy Badger is a browser extension that automatically learns to block invisible trackers.
Firefox Add-ons | Protects your privacy by blocking spying ads and invisible trackers.
Chrome Web Store | Privacy Badger protects you from trackers as you surf the web!
`about:extensions` | Privacy Badger protects you from trackers as you surf the web!
Twitter | I eat cookies and stop online tracking... nomnomnom

Anywhere else?

@bcyphers @andresbase Shall we standardize on variants (makes sense to say "browser extension" in some places but not others) of "automatically learns to block invisible trackers"? Twitter might be special though and should maybe be left alone, I dunno.

For the "about" link on homepage, we can use the same text we use in the README and extension listings (https://github.com/EFForg/privacybadger/issues/1675#issuecomment-391375664).

**Comment by andresbase** [comment]
Makes sense to standardize everything except twitter to: "Privacy Badger blocks spying ads and invisible trackers" or "Privacy Badger is a browser extension that blocks spying ads and invisible trackers" (Switching browser extension to browser addon in Firefox).

About in one of the drafts:
> Privacy Badger is a browser extension that automatically learns to block invisible trackers. Instead of keeping lists of what to block, Privacy Badger learns by watching which domains appear to be tracking you as you browse the Web.

> Third-party tracking—that is, when advertisers and websites track your browsing activity across the web without your knowledge, control, or consent—is an alarmingly widespread practice in online advertising. Privacy Badger puts you back in control by spotting and then blocking third-party domains that seem to be tracking your browsing habits.

> Although Privacy Badger blocks many ads in practice, it is more a privacy tool than a strict ad blocker. Privacy Badger encourages advertisers to treat users respectfully and anonymously rather than the industry status quo of online tracking

> Privacy Badger sends the [Do Not Track signal](https://www.eff.org/issues/do-not-track) with your browsing. If trackers ignore your wishes, your Badger will learn to block them. Privacy Badger starts blocking once it sees the same tracker on three different websites.

Is that too long? What is redundant? Are we saying the most important thing in the first paragraph?

**Comment by ghostwords** [comment]
The thing about "spying ads and invisible trackers" is that it doesn't say anything about what makes Privacy Badger different (you could say it about any adblocker probably), and "automatically learns to block invisible trackers" does. Does that make sense?

**Comment by ghostwords** [comment]
The "about" draft: half of it matches our [GitHub README](https://github.com/EFForg/privacybadger#privacy-badger-) (and consequently add-on listings text), but the middle two paragraphs are different. So it's close but I am not sure we need to have different text there. Maybe the middle two paragraphs are more FAQ material, and we already address what 3rd-party trackers are and whether we block ads there.

**Comment by DJCrashdummy** [comment]
the tagline from github is the best of the listed ones, but still with room for improvement: IHMO the most important to mention is that it is **(continuously/automatically) learning** and **blocks trackers**...
let me repeat an idea mentioned in [an other comment](https://github.com/EFForg/privacybadger/issues/1603#issuecomment-329459204): _"... is a learning/heuristic non-consensual tracking blocker."_ - this may not be really catchy and is rather explaining, but it is just for brainstorming and i'm not a PR-guy. :wink: 

@andresbase concerning your suggestion for the tagline: please read the 2nd bigger paragraph at https://github.com/EFForg/privacybadger/issues/1603#issuecomment-329459204 (*Why isn't Privacy Badger blocking first-party ads?*).

yes, twitter seems to be the one place for bidirectional (direct) communication, so it may be reasonable to keep separate.

---

yes, IMHO also the longer texts/explanations should be in sync when possible... this also eases maintenance: if something changes, change it at its source and simple copy&paste it.

all 4 paragraphs from @andresbase's suggestion are pretty good written and should be used (somewhere, even if just in the FAQs).
if it is too much for a quick introduction maybe the 2nd paragraph can be left out (since it is more of a general explanation) and adding the 3rd paragraph after the two identical ones may also be good idea.

**Comment by ghostwords** [comment]
All taglines (besides on Twitter) have now been standardized on "Privacy Badger automatically learns to block invisible trackers."

**Comment by ghostwords** [comment]
There is always room for improvement, but we should be good for now.
