### ISSUE TITLE
Long hostnames in list of blocked/allowed domains are trunacted. Unable to determine if I should unblock or not.

### ISSUE THREAD

**Issue by elnerd** [EFForg/privacybadger#1700]
[Image showing the problem](https://snag.gy/IVjB6N.jpg)

The problem is that I cannot see what the full hostnames, and thus unable to determine which I want to unblock.

I've encountered the problem on the following link:
http://www.vg.no/nyheter/utenriks/spania/ni-sendt-til-sykehus-politiet-bruker-makt-for-aa-stanse-valget/a/24153514/

**Comment by elnerd** [comment]
Adding image showing problem:

![image](https://user-images.githubusercontent.com/10955996/31054794-b521a2fa-a6ba-11e7-87ea-9f55109994dd.png)

**Comment by ghostwords** [comment]
Looks like the tooltip is also broken:

![screenshot from 2017-10-01 11 46 53](https://user-images.githubusercontent.com/794578/31056351-5187869a-a69e-11e7-93e4-7a2d12011055.png)

**Comment by ghostwords** [comment]
I think these are all `damoh.vgtv.no` subdomains. Grouping them under the parent domain would help: https://github.com/EFForg/privacybadger/issues/888#issuecomment-239416153.

The immediate solution though would be to use CSS (`text-overflow: ellipsis`) for specifying what to do with too-long messages, instead of cutting them off at fixed character length with JavaScript.

**Comment by terrorist96** [comment]
This was also noted here
https://github.com/EFForg/privacybadger/issues/1015#issuecomment-264499789

**Comment by ghostwords** [comment]
Oops, sorry, we missed ticketing that. Will be fixed in #1704.
