### ISSUE TITLE
Add some iraiser.eu subdomain to mdfp or yellow list

### ISSUE THREAD

**Issue by milouse** [EFForg/privacybadger#1721]
Hi,

We are a tiny company in France, working to help NGOs collect funds in various european countries. For different historical reasons, the websites we create for our customers contains links to js, css or image files on different subdomain of our main corporate domain. These domain are rarely the same as the customer main domain and thus, we appear in red even if we only serve css or pictures.

These different subdomains help us to serve very different contents to our customers and thus I don't think there is a viable surrogate to cover all our customizations.

I've add a [.well-known/dnt file](https://github.com/EFForg/privacybadger/issues/781), which reflects the fact that we do not use this domain to track anything, just serving content. It would be great if you accept to put this subdomains to the multi-domain first parties list or at least the yellow one:

* cdn.iraiser.eu
* libs.iraiser.eu
* web2.iraiser.eu
* *.igive.iraiser.eu

Here is a quick list of brocken sites:

* http://www.inactietegenkanker.nl/
* http://www.inactievoordedaniel.nl/
* https://macollecte.curie.fr/

And the corresponding http://www.inactietegenkanker.nl/.well-known/dnt/ file:

```
{
  "tracking": "N",
  "controller": "https://www.iraiser.eu/legal-informations/",
  "same-party": [
    "cdn.iraiser.eu",
    "libs.iraiser.eu",
    "web2.iraiser.eu",
    "*.igive.iraiser.eu"
  ]
}
```

Thank you very much.

**Comment by ghostwords** [comment]
Hello! I'll be available to fully review your request in about a week. Let me know if you need me to look at it sooner.

Regardless, if domains like `cdn.iraiser.eu` are used only for serving content and never tracking, they sound compliant with the [EFF Do Not Track Policy](https://www.eff.org/dnt-policy). If that's the case, you could post the policy on those domains, and then Privacy Badger will know to treat them specially. (I'm assuming these domains are only getting picked up by Privacy Badger because of broadly-scoped cookies from the website hosted at the same base domain.)

**Comment by ghostwords** [comment]
Could you run the following JavaScript code in your Privacy Badger's background page console and let us know what it shows? For more information and instructions for getting to the background page, see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.

```javascript
(function () {
  const STR = "iraiser";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by milouse** [comment]
Hi!

Thank you for your time. Sorry for not having answering your previous comment, I don't take time to try anything :(

I've just run your command and here is the result:

```
**** ACTION_MAP for iraiser 
www.iraiser.eu {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508430850553
} 
issfrontapidev.iraiser.eu {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1508675336238
} 
iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
} 
libs.iraiser.eu {
  "userAction": "user_block",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508462570921
} 
igive-iraiser.s3.amazonaws.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508068051620
} 
cdn.iraiser.eu {
  "userAction": "user_block",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508299121540
} 
grids.iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508292954590
} 
donner-esperanceruralites-org.iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1505674967901
} 
diocese-dijon-soutenir-eglise-fr.iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1505828097355
} 
issfrontdev.iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1505713598062
} 
issapi.iraiser.eu {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1505760521179
} 
web2.iraiser.eu {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508108353510
} 
cdn-h1.iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1507927075265
} 
iss-api-11stedenzwemtocht.iraiser.eu {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508634379581
} 
inactietegenkanker.igive.iraiser.eu {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508136182335
} 
apivalidation.iraiser.eu {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508178053054
} 
**** SNITCH_MAP for iraiser 
iraiser.eu [
  "localhost",
  "poc_vuejs.loc",
  "zwemelfstedentocht.nl"
]
```

**Comment by milouse** [comment]
Oh, I just found the preferences of privacy badgers. The `"userAction": "user_block"` alert me on some of the previous line, thus I purge my privacy badger history in the addons preference regarding all iraiser domains. After a browser restart, It seems our domains are not blocked anymore by default. I may have done thing correctly with my dnt files.

Sorry for the noise.

**Comment by ghostwords** [comment]
I think we still have a problem ... Your Privacy Badger learned to block `issapi.iraiser.eu` because it saw it perform tracking on pages belonging to three distinct domains, `localhost`, `poc_vuejs.loc` and `zwemelfstedentocht.nl`. (Privacy Badger also saw tracking by `issfrontapidev.iraiser.eu`, but fewer than on three distinct domains.) Once Privacy Badger decided to block `issapi.iraiser.eu`, it also marked the parent domain (`iraiser.eu`) for blocking. At that point, any other subdomains of `iraiser.eu` will also be blocked.

Clearing Privacy Badger data reset its learning, but if Privacy Badger learned to incorrectly block your domains once, it will probably learn to do the same thing again.

Since your domains are used only for serving content and never tracking, they sound compliant with the [EFF Do Not Track Policy](https://www.eff.org/dnt-policy). If that's the case, you could post the policy on each compliant domain, and then Privacy Badger will know to treat those domains specially.

**Comment by ghostwords** [comment]
@milouse What do you think about my above suggestion?

**Comment by milouse** [comment]
Sorry for my silence. I agree with your suggestion, however declaring such a policy require an authorization and discussion in my company, hence the delay. I've no data yet to share with you about it. Thank you for your patience. This issue can be close for now as I've all the information to understand and fix stuff on our side.

**Comment by ghostwords** [comment]
Sounds good, thank you for the update!
