### ISSUE TITLE
Flagging sites that aren't even referenced - usage note

### ISSUE THREAD

**Issue by valdisk** [EFForg/privacybadger#1750]
Just a heads up - more of a doc issue than a bug.

Having the SearchBar extension installed and enabled will result in the selected search engine(s) showing up in the "this page has trackers" list, even if the page doesn't reference them.

(Guess who just spent an hour trying to figure out why pages from our Zabbix server showed up as having trackers from www.wolframapha.com :)

**Comment by ghostwords** [comment]
[SearchBar](https://chrome.google.com/webstore/detail/searchbar/fjefgkhmchopegjeicnblodnidbammed?hl=en) seems to automatically inject `favicon.ico` from `www.google.com`, `www.youtube.com` and `www.wolframalpha.com` on all pages you visit. These requests get and set cookies.

**Comment by ghostwords** [comment]
This is seems like sloppy coding leading to a privacy breach on the part of SearchBar. Privacy Badger is just doing its job.

**Comment by valdisk** [comment]
But here's the thing - SearchBar may do that - but PrivacyBadger would flag things that were never referenced.  I first got looking at it because pages from our Zabbix server showed wolframalpha.com even though all of IPvFoo, tcpdump, and 'view source' only made one connection to one server - our Zabbix server.

And a reference never made can't be used as a tracker....

**Comment by ghostwords** [comment]
I'm not sure why you didn't see `favicon.ico` being fetched from `www.wolframalpha.com`. I can tell you it wouldn't be in the source of the page since the resource gets injected dynamically by SearchBar. You should be able to see these resources in the Elements panel and see the requests for these resources in the Network panel of [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/).
