### ISSUE TITLE
What causes a domains to be on both the MDFP list and yellowlist?

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1764]
I see 61 domains on both lists.  What makes a site need both lists to function?

amazon.com
ancestry.com
apple.com
archive.org
aspnetcdn.com
azureedge.net
blogger.com
com.com
ebay.com
ebayimg.com
ebayrtm.com
ebaystatic.com
fbcdn.net
flickr.com
ggpht.com
github.com
go.com
googleusercontent.com
googlevideo.com
gstatic.com
guardian.co.uk
imgur.com
jtvnw.net
kinja.com
kinja-static.com
microsoft.com
microsoftonline.com
mozilla.org
msn.com
netflix.com
nflxext.com
nyt.com
nytimes.com
openlibrary.org
paypal.com
phncdn.com
reddit.com
redditmedia.com
redditstatic.com
shopify.com
ssl-images-amazon.com
steampowered.com
storage.googleapis.com
tripadvisor.com
ttvnw.net
twimg.com
twitch.tv
twitter.com
wikidata.org
wikimedia.org
wikipedia.org
wordpress.com
wp.com
yahooapis.com
yandex.net
yandex.ru
yimg.com
youtube.com
youtube-nocookie.com
ytimg.com
zopim.com

**Comment by ghostwords** [comment]
The [multi-domain first parties list](https://github.com/EFForg/privacybadger/blob/8dbb4bec28d2f4b1c838dd2375a0f8eea583b02b/src/js/multiDomainFirstParties.js#L7) exists to tell Privacy Badger that the same company owns, for example, `media-amazon.com` and `audible.com`, which means we should treat `media-amazon.com` resources on `audible.com` pages as first (and not third) parties. This serves to resolve breakages caused by blocking those resources on `audible.com`.

To continue our example, if `media-amazon.com`-related breakages only ever exist on Amazon properties, there is no (or, no longer any) reason to have `media-amazon.com` on the yellowlist. Some domains might be on the yellowlist and on the MDFP list because we had the yellowlist before we had the MDFP list. Others might legitimately belong on both because they do appear in both first- and third-party contexts.

See also [our work-in-progress guide to fixing broken sites](https://github.com/EFForg/privacybadger/blob/8dbb4bec28d2f4b1c838dd2375a0f8eea583b02b/doc/fixing-broken-sites.md#resolve-the-breakage) and #1593.

**Comment by ghostwords** [comment]
I edited your description to make the domain list collapsible.
