### ISSUE TITLE
With 3p Cookies blocked in Chrome, JS SetCookie events seem to be detected but don't cause blocking

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadger#1851]
(As discussed on Mattermost). I think I the issue I was observing with lots of unblocked trackers on pages like [Chicago Tribune articles](http://www.chicagotribune.com/news/local/breaking/ct-met-university-of-chicago-steve-bannon-petition-20180130-story.html) was several different issues at once. In addition to [circumvention of content blocking by that page](https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful#instart-logic), it seems that when third party cookies are blocked in Chrome, PB notices the set cookie events but doesn't actually red/yellow list because of them?

**Comment by svandragt** [comment]
This started happening since the latest update as it used to work before the 2018.1.30 version (Vivaldi)

**Comment by ghostwords** [comment]
Hi @svandragt, could you describe how you noticed this issue?

**Comment by svandragt** [comment]
@ghostwords I'm now wondering if instead Privacy Badger crashed? Instead of a badge with the number of blocked requests, and a list of domains and their status, I saw the following:
![missing-options](https://user-images.githubusercontent.com/594871/35684221-23177fce-075e-11e8-8bb5-cd8b382a27ad.png)

I just happened again here on GitHub. Re-enabling the extension and reloading fixed it so I now unsure if it's 3p cookies related

**Comment by ghostwords** [comment]
@svandragt Looks like another Vivaldi user is experiencing the same issue: #1855.

**Comment by pdbits** [comment]
@ghostwords Facing the same issue, even with the same error in console, but reloading/reinstalling doesn't fix the issue.

**Comment by svandragt** [comment]
I'll move my discussion to #1855 as I did only notice it after Vivaldi updating as well.

**Comment by ghostwords** [comment]
@pde Privacy Badger is indeed affected when third-party cookies are disabled, as Chrome seems to block writing of cookies and localStorage by third parties. Privacy Badger still gets to learn from Set-Cookie headers sent by third parties, however.

I am not sure there is anything to do here other than to update the [FAQ entry for what happens when you disable third-party cookies](https://github.com/EFForg/privacybadger/wiki#does-privacy-badger-still-work-when-blocking-third-party-cookies-in-the-browser).

**Comment by ghostwords** [comment]
We should investigate what the Privacy Badger experience is like with third-party cookies disabled, see whether we can do anything to improve it (such as perhaps detect failed JavaScript cookie events), and document the differences using Badger with and without third-party cookies.

**Comment by ghostwords** [comment]
FAQ entry updated: https://github.com/EFForg/privacybadger/wiki/Home/_compare/0c3cb962825dd2577304a71dae6d8da7ae87a3fe...a4503008e228da461614ecc2bd09e381c3c4c46a

**Comment by ghostwords** [comment]
This answer now lives on the homepage FAQ: https://www.eff.org/privacybadger/faq#Does-Privacy-Badger-still-work-when-blocking-third-party-cookies-in-the-browser
