### ISSUE TITLE
intercom.io is blocked

### ISSUE THREAD

**Issue by skorokithakis** [EFForg/privacybadger#1917]
Intercom.io provides support chat widgets, so blocking it is breaking functionality on some sites. The two domains I noticed blocked (and that make intercom.io work when unblocked) are "api-iam.intercom.io" and "widget.intercom.io".

**Comment by ghostwords** [comment]
Hello, and sorry for the delayed response.

Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "intercom";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
Other chat widget issues: #752, #1873.

**Comment by skorokithakis** [comment]
Here you go:

```
**** ACTION_MAP for intercom 
intercom.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1493289314754
} 
api-iam.intercom.io {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1521953781574
} 
nexus-websocket-a.intercom.io {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1493221052163
} 
blog.intercom.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1517446226231
} 
app.intercom.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1522776472260
} 
insideintercom.disqus.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1517399843227
} 
nexus-websocket-b.intercom.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1521779553302
} 
nexus-long-poller-a.intercom.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1522089331265
} 
widget.intercom.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1522491548868
} 
**** SNITCH_MAP for intercom 
intercom.io [
  "mailgun.com",
  "ably.io",
  "logojoy.com",
  "getcastor.com"
]```

**Comment by skorokithakis** [comment]
This is on https://onesignal.com/, by the way.

**Comment by ghostwords** [comment]
So I think ideally this would be a replacement widget (#1467). Privacy Badger learns to block `intercom.io`, at which point Privacy Badger will start injecting Intercom replacement widget code into pages with blocked `intercom.io` resources. The code would show a Privacy Badger-co-branded placeholder that, when clicked, will inject and allow `intercom.io` for this one page load.

One problem here is that Intercom doesn't seem to have a page location selector as part of its HTML tag, so if we made a replacement widget for Intercom, we'd be making more assumptions than usual: such as assuming where Intercom will want to display (so that we can display our placeholder button there). It looks like we will also need to support some bits of Intercom's API (such as to activate our replacement widget via `Intercom('show')` page calls) .

Should we try this approach? We could also just add all of `intercom.io` to the yellowlist, which will deny cookies and localStorage and will otherwise allow `intercom.io` resources to load. It's simpler for us, but it creates greater privacy exposure for users. What if you don't want to interact with Intercom widgets at all, why should you communicate with their servers?
