### ISSUE TITLE
PrivacyBadger breaks Cisco Spart Video/Audio Call

### ISSUE THREAD

**Issue by zioalex** [EFForg/privacybadger#1973]
With the plugin installed, even if disabled for the site, I cannot do any Cisco Spark call.

The only way to get it working is to disable completely the addons.

Software Version:
OS: Linux Sabayon
FF 58.0.1 (64bit)
Privacy Badger 2018.04.10

**Comment by ghostwords** [comment]
Oh I see, you are on Firefox. I am not sure there is an extension like WebRTC Network Limiter for Firefox, one that lets you overwrite this WebRTC setting to the browser default. If there is, feel free to try that, otherwise, could you please test to see that you have the same problem in Chrome, and that setting up WebRTC Network Limiter works around it?

**Comment by zioalex** [comment]
Not possible to try in Chrome because Spark is not supported there. I found
this addons (https://addons.mozilla.org/en-US/firefox/addon/webrtc-control/)
for FF but not sure that is doing what is needed. Can you please clarify
what the Chrome plugin should do?

**Comment by ghostwords** [comment]
Yeah, I'm not sure that will do it because we need an add-on that will relax (not harden) the setting. Oh well, we could try it by hand though.

Could you run the following script in your Badger's background page console and then try using Spark?
```javascript
chrome.privacy.network.webRTCIPHandlingPolicy.set({value: "default"});
```
To get to the background page console in Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by zioalex** [comment]
I tried what you suggested but I receive an "undefined" message:

**Comment by ghostwords** [comment]
That's OK, it doesn't mean this didn't work. Does Spark work (you should reload already open Spark tabs) after executing the above JavaScript on Privacy Badger's background page?

**Comment by zioalex** [comment]
Hi Alexei,
that is good. Now it worked. How can I make this change permanent?
Thanks
Alessandro

Alessandro Surace
[image: https://twitter.com/zioale] <https://twitter.com/zioale>

**Comment by ghostwords** [comment]
OK thank you for verifying! Please subscribe to #1099 (which will let you properly disable WebRTC protection) for updates.
