### ISSUE TITLE
First-party scripts should not run when privacy badger is disabled

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2025]
Brought up in #2018. The Twitter and Facebook link-unwrapping scripts run even when privacy badger is disabled, and this could make it hard for users to figure out whether PB is breaking something on one of those sites. We should add a check for `badger.isPrivacyBadgerEnabled()` before running each script.

**Comment by ghostwords** [comment]
This is related to #1865. We don't have a cross-browser way of conditionally injecting a before-anything-else-happens content script. We also aren't able to synchronously communicate between content scripts and the background page.

Since messaging seems like the most straightforward way to disable Facebook/Twitter scripts, there will be a (probably sub-second) delay before the scripts will get to do their thing when enabled. This is probably fine for link unwrapping purposes.

**Comment by ghostwords** [comment]
See #1859 for the fix for a similar situation.

**Comment by Jsnhlbr5** [comment]
I am looking to work this, but would it make sense to wait for #2016 to get merged, since it is making significant changes to at least the Facebook script?

**Comment by ghostwords** [comment]
It's fine, I'll handle the merging, whichever way it ends up going.
