### ISSUE TITLE
privacy-badger17

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadger#2075]
Why is the link to Privacy Badger: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/

Why is it not just set to this?: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger/

**Comment by ghostwords** [comment]
Good question. I can change the URL, but that would probably break all direct links to the current listing, which I don't want to do. Opened https://github.com/mozilla/addons/issues/743 to get help with setting up a redirect.

**Comment by davidhedlund** [comment]
@ghostwords Thanks.

**Comment by ghostwords** [comment]
Since this doesn't cause any problems (besides being a visual nit), and breaking existing links will cause problems, and [setting up a proper redirect from old to new listing URLs isn't supported](https://github.com/mozilla/addons/issues/743#issuecomment-400103111), I am going to close this as something we can't/shouldn't do at this time.

**Comment by davidhedlund** [comment]
@ghostwords Yes, I read the other issue and I understand. But closing the issue won't help since the goal here is to fix it once it's supported to add redirects. I'd rather label it "long-term" or anything.

**Comment by ghostwords** [comment]
We have too many open issues. This is easy enough to find and reopen if we want to later.

**Comment by davidhedlund** [comment]
@ghostwords Alright, I give up on this one. Thank you for taking your time again.
