### ISSUE TITLE
Please add et4.de to the yellow list

### ISSUE THREAD

**Issue by technik-kvz** [EFForg/privacybadger#2097]
The sites implements scripts etc. for tourism: for example event search/calendar etc. and is often used as external script source on public sites.

**Comment by technik-kvz** [comment]
See pull request #2098.

**Comment by ghostwords** [comment]
Could you also (or instead) provide a few example sites that use your eT4? Three would be great.

**Comment by ghostwords** [comment]
I was able to reproduce Privacy Badger learning to block `et4.de` domains by visiting the following three pages:
- https://www.feengrotten.de/Besuch-planen/kalender/Veranstaltungskalender/#/de/saalfeld-tourismus/default/search/Event/view:list/sort:chronological/mode:next_months/calView:agendaWeek
- https://www.zinnowitz.de/infos/veranstaltungen#/de/zinnowitz/default/search/Event/view:list/sort:chronological/mode:next_months/calView:agendaWeek
- https://www.ostfriesland.de/veranstaltungen/de/ostfriesland/streaming/search/Event/view:list/sort:chronological/mode:next_months,12/calView:agendaWeek

**Comment by ghostwords** [comment]
It seems this happens because of various (ASP.NET?) session cookies.

Would (some of) eT4 subdomains be compliant with [EFF's Do Not Track policy](https://www.eff.org/dnt-policy) by any chance? If you are willing and able to abide by the policy's requirements on these domains, posting the policy on each compliant domain (`pages.et4.de`, ...) will tell Privacy Badger to always allow loading of resources from those domains.

**Comment by technik-kvz** [comment]
Thank you for your investigation, I will forward this to the developers of et4.de.

**Comment by ghostwords** [comment]
Hello! Was there any response from eT4?

**Comment by technik-kvz** [comment]
They just recommenced to use their page via subdomain and cname entry in dns, https wouldn't like that, there is more necessary but if they make the right changes to the channels that might work. No comment to privacy badger ticket at all :(.
