### ISSUE TITLE
New tracking methods. Anything that can be done at PrivacyBadger side? "Who Left Open the Cookie Jar? A Comprehensive Evaluation of Third-Party Cookie Policies"

### ISSUE THREAD

**Issue by popcornenthusiast** [EFForg/privacybadger#2137]
> Cookies have become an important aspect of the modern-day web. By default, browsers automatically attach cookies to all HTTP requests. This allows users to keep track which items they have added to their online shopping basket, or simply to log in to their favorite websites. However, cookies may also be exploited for more nefarious goals: users' online activies are tracked at large-scale by various advertising companies, or so-called cross-site attacks can be used to take over the account of an unwitting user. As a response to this increasing threat surface, a variety of defense mechanisms have been developed: either as anti-tracking or ad-blocking browser extensions, or as built-in browser features such as the Tracking Protection in Firefox, or SameSite cookies, which can be highly effective at thwarting cross-site attacks.
> 
> An important prerequisite for these privacy- and security-enhancing features to function properly, is that all requests need to comply with the imposed cookie policies. As browsers have become enormously complex, certain edge-cases may have been overlooked or the interplay of specific features may have unwanted side-effects. In our research, we created a framework to verify whether all imposed cookie- and request-policies are correctly applied (will be made available soon). Worryingly, we found that most mechanisms could be circumvented: for instance for all ad-blocking and anti-tracking browser extensions we discovered at least one technique that could bypass the policies. For the technical details of these findings, we invite you to read our paper, which was presented at USENIX Security ’18.
> 
> We have been working with browser vendors and extension developers to mitigate the discovered issues. To verify whether you are affected by our detected bypasses, feel free to explore the data on this website (please note that we are still working to have the most up-to-date information available).

The project's website: https://wholeftopenthecookiejar.eu/

The paper: https://wholeftopenthecookiejar.eu/static/tpc-paper.pdf
OR
https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-franken.pdf

**Comment by bcyphers** [comment]
Thanks for the links. We're aware of the research, and are planning to look into it more over the next few weeks to see what Privacy Badger can do. If you have any specific suggestions, please let us know.

**Comment by ghostwords** [comment]
gorhill's response: https://twitter.com/gorhill/status/1030071494263615489

**Comment by ghostwords** [comment]
Related to #1010, probably others.

**Comment by popcornenthusiast** [comment]
Thanks for the answers!

I'm not a developer, but here it's what I think:

1) Block every cookie from third-party domains using a XHR request;
2) Block every cookie from third-party domains using a WS request (and not every connection, as I understand from #1010);
3) Block meta-refresh redirections to third-party cookie-blocked domains AND blocked domains;
4) Wipe out the "referrer" header from connections to third-party cookie-blocked domains AND blocked domains (though, I'm guessing, this would be redundant);
5) And one more thing, though not directly related: Block connections when the url carries user-agent info as a string.

**Comment by bcyphers** [comment]
After reading the paper, here are a few of the issues that might apply to us:

1. Websockets-based tracking. We currently only intercept http(s) requests, not ws:// or wss://. This is known and documented in #1010; it's easy to fix but would likely lose us a portion of our users. I'm in favor of doing this sooner rather than later and being very clear about our messaging.
2. AppCache API tracking. Although the API is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache#Browser_compatibility), old websites still use it, and most browsers still support it. The problem here is that all AppCache requests have `details.tabId = -1`, which makes it hard to attribute requests to a specific first-party domain. I'm not sure how Privacy Badger handles these, and need to look into it more.
3. Likewise, [service workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) have the same issue, at least in Chrome. Need to investigate whether PB can block requests to trackers made using this api.
4. Redirects. We completely ignore main frame requests, so a
