### ISSUE TITLE
Translation issue in pop up menu

### ISSUE THREAD

**Issue by Urides** [EFForg/privacybadger#2268]
Hi,

I've noticed a problem between the singular and plural form in french :

![pluriel pb](https://user-images.githubusercontent.com/24555008/51084376-c6072b00-1728-11e9-9964-6feba4cab857.png)

With 0 tracker, we should read : 0 traceur potentiel (with no "s")

Thanks

**Comment by ghostwords** [comment]
Thanks for letting us know!

Could we reword the [`popup_instructions` message](https://github.com/EFForg/privacybadger/blob/4b9d51098fc2646eefad06ff827c9cbac9c60599/src/_locales/fr/messages.json#L373) to avoid this issue? So instead of

>Privacy Badger a détecté $COUNT$ traceurs potentiels sur cette page. Ces curseurs vous permettent de modifier la façon dont ils sont gérés. ...

we would have (the equivalent of)

>Potential trackers detected: $COUNT$. Ces curseurs vous permettent de modifier la façon dont ils sont gérés. ...

This message is used when there are third-party domains on the page (so we show sliders), but either none of them are "potential trackers", or we have more than one potential tracker. This means `$COUNT$` could be 0 or 2+.

There is a separate message for when there is exactly one potential tracker (`popup_instructions_one_tracker`), and for when there are no third-party domains at all (`popup_instructions_no_trackers`).

**Comment by Urides** [comment]
A reword would not fix the problem. Grammatically speaking, "Potential trackers detected:" would have to be singular if $COUNT$ is 0 or 1 and plural if 2+.

**Comment by ghostwords** [comment]
@Urides @bcyphers @andresbase What if we avoid this problem by using the "No trackers detected. Hooray for privacy!" message in the case when no tracking domains, but one or more other third-parties are present? Screenshot:

![screenshot from 2019-01-22 12 02 32](https://user-images.githubusercontent.com/794578/51552139-f55f1b80-1e3d-11e9-85e1-df5ea1dc3c2f.png)

**Comment by ghostwords** [comment]
In French:

![screenshot from 2019-01-22 12 08 16](https://user-images.githubusercontent.com/794578/51552366-6f8fa000-1e3e-11e9-9d0d-d4a1c591762f.png)

**Comment by Urides** [comment]
That would work!

**Comment by andresbase** [comment]
Yeah that works.
