### ISSUE TITLE
Will the proposed Manifest V3 changes to Chrome break Privacy Badger?

### ISSUE THREAD

**Issue by zikalify** [EFForg/privacybadger#2273]
https://www.theregister.co.uk/2019/01/22/google_chrome_browser_ad_content_block_change/

**Comment by ghostwords** [comment]
It's not entirely clear yet, but at this point it seems that the changes proposed in the [Manifest V3 document](https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8/edit) are made to support basic list-based blockers only. It's not clear how Manifest V3 would allow for more complex extensions like uBlock Origin, uMatrix or Privacy Badger. I would like to learn more about this situation from Chromium developers.

**Comment by ghostwords** [comment]
[Devlin writes](https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/veJy9uAwS00/TXDTsyG9GgAJ):
>Our goal is not to break extensions.  We are working with extension developers to strive to keep this breakage to a minimum, while still advancing the platform to enhance security, privacy, and performance for all users.
>...
>The most helpful feedback for us is the exact cases that this would impact, their importance, and the reasons they are impossible through either the declarative API or through other extension APIs.

**Comment by ghostwords** [comment]
### An overview of the Manifest V3 proposal's impact upon Privacy Badger

Privacy Badger is a browser extension that automatically learns to block invisible trackers.

>Instead of keeping lists of what to block, Privacy Badger learns by watching which domains appear to be tracking you as you browse the Web. Privacy Badger sends the Do Not Track signal with your browsing. If trackers ignore your wishes, your Badger will learn to block them. Privacy Badger starts blocking once it sees the same tracker on three different websites.

The [Manifest V3 proposal](https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8/edit) thoroughly breaks this description. It appears that Privacy Badger will no longer be able to dynamically learn to block trackers, report what it blocked on a page, block cookies from being set or sent, strip referrer headers, nor properly support [EFF's Do Not Track policy](https://www.eff.org/dnt-policy).

If you remove what makes Privacy Badger unique, replacing it with basic list-based blocking, what are you left with?

#### Replacing  persistent background pages with ServiceWorkers
A non-persistent event-driven background page does not work well for extensions that need to keep ephemeral state.
- Privacy Badger maintains per-tab data that includes things like which third-party domains were detected and/or blocked on the page.
- It may be possible to continuously save and restore state from storage as a workaround, but this seems counter to the stated performance goals of moving away from persistent background pages. It seems that persistent background pages are a much better fit for certain (stateful) types of extensions.
- As Privacy Badger requires the webRequest API (for examining/modifying headers, noting third-party domains, and blocking/redirecting requests), a persistent background page seems required as per [Chrome extension docs](https://developer.chrome.com/extensions/background_pages#persistentWarning):

    >The webRequest API is incompatible with non-persistent background pages.

There are likely other issues (will a ServiceWorker background page support functioning in Incognito contexts, which is essential for privacy and security extensions?), but they are eclipsed by the fundamental mistake of trying to shoehorn stateful extensions into an exclusively event driven model.

#### Restricting origin access / Manifest Host Permission Specification

Making users confirm extension access (`host_permissions`) does not seem to make sense for general-purpose content blocking (adblocker/privacy/security) extensions. Outside of edge cases (for example, a Facebook.com-specific extension), content blockers need access across all URLs. Redundantly prompting users for permission to run these scripts (on top of the existing notification users see when initially installing Privacy Badger) will be unhelpful and confusing.

As [Chrome extension docs for permissions](https://developer.chrome.com/extensions/permissions) state:
>Use required permissions when they are needed for your extension’s basic functionality.

#### Dynamic Content Scripts
Many of Privacy Badger's content scripts need to run on all pages in order to do things like detect localStorage-based tracking and canvas fingerprinting, or deny JavaScript access to cookies and localStorage to "yellowlisted" third-party domains.

It would be great to finally have dynamic, before-anything-else injection of content scripts (https://crbug.com/478183). However, as per the `host_permissions` note above, it doesn't make sense to make users have to re-confirm this access via permission dialogs.

#### WebRequest

Removing "blocking" (synchronous request/response interception) from `webRequest` will break core Privacy Badger functionality.

The `declarativeNetRequest` API is an entirely inadequate replacement as it supports `onBeforeRequest` blocking and redirection only (not header/body inspection or modification), and seems to support (a limited number of) hardcoded rules only.

- Privacy Badger needs to dynamically create rules.
- Privacy Badger's rules interact with each other. A request that would be blocked may be overriden to "cookie-blocked" instead by the user, or it may be registered as a DNT-compliant domain and thus allowed.
- Rules need to be further qualified by things like whether the request/response domain is third-party to the top-level document.
- Privacy Badger needs to report what it did (blocked, etc.) on a page.
- Privacy Badger needs to be able to modify content headers (block cookies, strip referrers, perhaps modify ETag headers, ...).
- Privacy Badger would benefit from being able to [modify response bodies like WebExtensions can in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData). The `webRequest` API should be gaining, not losing functionality.
- Privacy Badger needs to encourage privacy-respecting ads by continuing to enforce the [EFF Do Not Track policy](https://www.eff.org/dnt-policy). This means Privacy Badger needs to continue being able to check blocked domains for declarations of DNT compliance.

The above is not meant to be an exhaustive list. The point is that it is a fundamental mistake to try to shoehorn all content intercepting extensions into the limited-by-design declarative model.

**Comment by Jab2870** [comment]
It looks like Google might be backtracking on this: https://www.zdnet.com/article/google-backtracks-on-chrome-modifications-that-would-have-crippled-ad-blockers/

**Comment by ablanathtanalba** [comment]
Has there been any followup or elaboration on what will be removed from the `webRequest` API? Devlin says in that statement that not all will be removed, but seems to hint that anything that goes beyond purely observational capabilities is on the chopping block. Does the PB team have a plan to make public a response similar to what the folks at Ghostery did?

**Comment by pipboy96** [comment]
Related: Eloston/ungoogled-chromium#706.

**Comment by twome** [comment]
This is what happens when the world becomes dependent on deeply evil monoliths of surveillance capitalism to provide basic communication tools like browsers 😞 . Chromium is open-source, but we live in the real capitalist world where developers need money to eat and pay rent - the rest of us don't have the resources to maintain a competing fork of Chromium, let alone the advertising budget and infrastructure of Google. We can kick up a stink, but without fundamental social change we are destined to fight a losing battle against constant encroachments on privacy and democratic rights such as this.

**Comment by pipboy96** [comment]
@twome Generally, such "rants" are off-topic here. @ghostwords hide please?

**Comment by pipboy96** [comment]
⚠️ **UPDATE: Blocking capabilities of webRequest are still being deprecated, see** https://github.com/uBlockOrigin/uBlock-issues/issues/338#issuecomment-495936668 (original post deleted) and commentary by @gorhill: https://github.com/uBlockOrigin/uBlock-issues/issues/338#issuecomment-496009417.

Thanks @Giltyhub for update!

**Comment by pipboy96** [comment]
See the issue in HTTPS Everywhere's repository for statements recently made by browser vendors: https://github.com/EFForg/https-everywhere/issues/17268.

**Comment by sillyjaybird** [comment]
@ghostwords I'm finding little _current_ info on MV3 generally and wondering if you've learned anything new about it's impact on Privacy Badger? Is any work being done to develop a MV3-compliant version of the extension?

**Comment by ghostwords** [comment]
You can read our latest update on the EFF blog: https://www.eff.org/deeplinks/2021/12/googles-manifest-v3-still-hurts-privacy-security-innovation. While the post doesn't go into Privacy Badger specifically, we talk about what happened around Manifest V3 in the last two years, what's (still) wrong with it, and how it could be better.

I have been participating in the [W3C WebExtensions Community Group](https://github.com/w3c/webextensions/) to advocate for extension developers and to raise awareness of the many problems with Manifest V3.

Privacy Badger in Manifest V3 is blocked by at least one (long-outstanding) bug, [Chromium Issue 102421: webRequest listeners not called after service worker stops](https://bugs.chromium.org/p/chromium/issues/detail?id=1024211).

**Comment by sillyjaybird** [comment]
@ghostwords I'm already familiar with the EFF post, Thanks for the specific example of an issue facing many developers.

**Comment by sillyjaybird** [comment]
@ghostwords Is there any development status of a MV3-compliant version of Privacy Badger other than your previous reply above?

**Comment by ghostwords** [comment]
Nope, https://github.com/EFForg/privacybadger/issues/2273#issuecomment-1009197551 is still the latest status.

**Comment by twome** [comment]
I permanently switched to Firefox when this happened (and hopefully we all realise Mozilla is subject to the same whims of private ownership & the global market as Google is).

I think this event serves as a very salient reminder that you can never truly address solve social problems with technical solutions alone. I have tremendous respect for all devs who give their time helping users sidestep or work around oppressive & exploitative technology, but we should all understand that, fundamentally, this kind of dynamic will persist *forever* until all users and software authors [democratically share the means of making and changing software](https://www.marxists.org/archive/marx/works/1867-c1/ch01.htm#S1) - which includes all currently private intellectual property - and that the only way to permanently achieve that is through [extralegal, democratically worker-led global revolution](https://www.marxists.org/archive/luxemburg/1900/reform-revolution/intro.htm).

**Comment by sillyjaybird** [comment]
Since the rollout of 2023 is fast approaching, is an MV3 compatible version of Privacy Badger in development?

**Comment by ghostwords** [comment]
Yes, I'm working on it. I'll post an update when we have something to share.

**Comment by sillyjaybird** [comment]
Thanks!

**Comment by sillyjaybird** [comment]
> Yes, I'm working on it. I'll post an update when we have something to share.
MV2 deprecation mid-June '24
[https://developer.chrome.com/blog/resuming-the-transition-to-mv3/](url)

**Comment by sillyjaybird** [comment]
@ghostwords MV2 deprecation slated for June '24. How is MV3 development going?
[https://developer.chrome.com/blog/resuming-the-transition-to-mv3/](url)

**Comment by ghostwords** [comment]
It's going! We've been making changes to prepare Privacy Badger for non-persistent background processes, be it an event page (Firefox) or an extension service worker (Chrome). We're now moving content filtering from `webRequest` to `declarativeNetRequest`.

**Comment by sillyjaybird** [comment]
@ghostwords Thanks for the update!

**Comment by dotproto** [comment]
@ghostwords, let me know if there's anything I can help with on the Firefox side of things.

**Comment by ghostwords** [comment]
Privacy Badger version 2024.5.30 is live in Chrome Web Store. You can get get this update now by visiting `chrome://extensions/`, enabling "Developer mode", and clicking the "Update" button.

Producing this version took months of running to stay in place. MV3-based Privacy Badger is not a "lite" version of Privacy Badger. It is functionally similar to MV2-based Privacy Badger, slightly better in some ways, and worse in other ways, some of which will get fixed over the coming months.

There are a bunch of known bugs and regressions (that I haven't documented yet). More troubling are the bugs that I don't know about yet.

**Comment by sillyjaybird** [comment]
@ghostwords Thanks for the update.

**Comment by sillyjaybird** [comment]
> It is functionally similar to MV2-based Privacy Badger, slightly better in some ways, and worse in other ways, some of which will get fixed over the coming months.
Can you please describe what MV3 version positives/negatives currently exist and which may be fixed?

**Comment by sillyjaybird** [comment]
> Privacy Badger version 2024.5.30 is live in Chrome Web Store. You can get get this update now by visiting `chrome://extensions/`, enabling "Developer mode" and clicking the "Update" button.
> 
> Producing this version took months of running to stay in place. MV3-based Privacy Badger is not a "lite" version of Privacy Badger. It is functionally similar to MV2-based Privacy Badger, slightly better in some ways, and worse in other ways, some of which will get fixed over the coming months.

Are you able to describe the feature pros and cons of the MV3 version and which may get fixed over time? Or will you do this later, e.g. via a EFF blog post, as development progresses or is finalized?

**Comment by ghostwords** [comment]
I've got to put out a few fires first. Afterwards, I'll be able to start documenting and generally sharing more. But there are few "pros". Manifest V3 is a huge mess. If Google wanted to, they could have rolled out a Manifest 2.5 with all of the pros and none of the cons, you know?

**Comment by sillyjaybird** [comment]
> I've got to put out a few fires first. Afterwards, I'll be able to start documenting and generally sharing more. But there are few "pros". Manifest V3 is a huge mess. If Google wanted to, they could have rolled out a Manifest 2.5 with all of the pros and none of the cons, you know?

I don't know how many developers contirbute to the project, but will you maintain both MV2 and MV3 versions or settle on the latter when it's more polished given MV3's shortcomings?

**Comment by ghostwords** [comment]
We will maintain MV2 Privacy Badger for as long as it makes sense to do so. Right now only Chrome is on MV3.

I think the biggest bright side here is that we shouldn't be far off from being able to offer Privacy Badger for Safari on macOS at this point.

**Comment by sillyjaybird** [comment]
@ghostwords ^^:)

**Comment by sillyjaybird** [comment]
Any news on developments regarding MV3 implementation in Privacy Badger?

**Comment by ghostwords** [comment]
Not yet! You can get release notifications by "watching" releases in this repository, or you can follow [@privacybadger@mastodon.social](https://mastodon.social/@privacybadger) on Mastodon.

I'm closing this issue as a Manifest V3 version of Privacy Badger has been live in Chrome for a few months now.

**Comment by sillyjaybird** [comment]
> I've got to put out a few fires first. Afterwards, I'll be able to start documenting and generally sharing more. But there are few "pros". Manifest V3 is a huge mess. If Google wanted to, they could have rolled out a Manifest 2.5 with all of the pros and none of the cons, you know?
> 
Have you put out those fires yet?

**Comment by ghostwords** [comment]
Yes, and we're working on the next update.

**Comment by Mikaela** [comment]
> We will maintain MV2 Privacy Badger for as long as it makes sense to do so. Right now only Chrome is on MV3.

Is there any guesstimate on for how long that is? I am coming from https://github.com/EFForg/privacybadger/issues/3061 having poorly remembered this issue and I was under mistaken impression that everything was MV3 since

> MV3-based Privacy Badger is not a "lite" version of Privacy Badger. It is functionally similar to MV2-based Privacy Badger...

---

> I'll be able to start documenting and generally sharing more. 

I guess that documentation will answer at least some of these questions

**Comment by ghostwords** [comment]
Our Edge and Firefox versions are still MV2. The main reason for staying on MV2 is that [MV3 is buggy](https://github.com/EFForg/privacybadger/issues?q=is%3Aissue%20label%3AMV3%20label%3Abug%20). At some point we will either be forced to migrate, or MV3 will become less buggy and more fully featured than MV2, in which case we will migrate voluntarily.

**Comment by sillyjaybird** [comment]
@ghostwords - Any new info about the MV3 version you can share?
