### ISSUE TITLE
Screencast-O-Matic

### ISSUE THREAD

**Issue by MLPAA** [EFForg/privacybadger#2357]
#### What is your browser and browser version?
Chrome

#### What is broken and where?
Blocked images created with the screen capture tool in Screencast-O-Matic

#### What is the "culprit" domain?
https://screencast-o-matic.com/

**Comment by ghostwords** [comment]
Related: https://bob3160.blogspot.com/2019/05/screencast-o-matic-and-privacy-badger.html

**Comment by ghostwords** [comment]
If I understand the problem correctly (let me know if I don't), Privacy Badger learns to block images hosted by `screencast-o-matic.com`. This happens because your Privacy Badger sees these images and thinks there is tracking going on. Once Privacy Badger sees the tracking happen on three different sites, it will block the tracking domain.

To work around this issue for yourself, you can move the slider for `screencast-o-matic.com` to "yellow" (allow to load but block cookies) or "green" (allow fully).

**Comment by ghostwords** [comment]
If `screencast-o-matic.com` does not actually track users, and if they are able and willing to abide by the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements on the domain, they could post the policy on `screencast-o-matic.com` (for example the following URL declares that www.eff.org is DNT-compliant: https://www.eff.org/.well-known/dnt-policy.txt), which will automatically tell Privacy Badger to always allow loading of resources from `screencast-o-matic.com`. You could point them to this post if they have any questions.

Closing for now, let me know if there is anything else I can help with.
