### ISSUE TITLE
Differing assessments of tracking domains, namely fonts.googleapis.com

### ISSUE THREAD

**Issue by ballsystemlord** [EFForg/privacybadger#2361]
I don't really think it makes a difference to my browsing experience, but I noticed that when using firefox vs. opera domains are rated differently with respect to who's tracking you. Granted, different websites might have different behaviors with different browsers but I wanted to file this just in the event that PB has problems detecting who's tracking us and who's not.
Opera version: 60.0.3255.70
Firefox version: 60.6.2esr
Running on top of Devuan (Debian) Linux.
AFAIK I have the latest version of PB installed on both browsers.
The place I'm seeing this is on sourceforge, in particular:
https://sourceforge.net/projects/linnix/
FF's PB says that fonts.googleapis.com is not tracking me and Opera's PB says that it is tracking me.

I might be able to find more examples if you need them. I've not done a lot of cross comparisons yet.

Thanks!

**Comment by ghostwords** [comment]
Hello! This might also be due to the other extensions you have installed, and the order they were installed in. I don't see tracking from `fonts.googleapis.com` in either Chrome or Firefox though. I wonder if your Badger considers it to be tracking in Chrome thanks to a bug.

Could you run our [debug code](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for `fonts.googleapis.com` and share the output?

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing for now.

**Comment by ballsystemlord** [comment]
Your link reads: 

> Try toggling individual blocked domains to "allowed," then reload the page. Keep doing so until you find the domain or domains which, when unblocked, allow the page to load correctly. This domain is the probable culprit, and you'll need it for later.

I'm not having a problem with rendering the webpage, just differing PB decisions with respect to 1 domain. Should I still follow this step or is it not applicable to my problem?
Thanks!

**Comment by ghostwords** [comment]
Yeah, that's not applicable. We already know the "culprit" domain (`fonts.googleapis.com`). I am asking to go through steps 2 and 3 though. Sorry for the confusion.

**Comment by ballsystemlord** [comment]
I did as you asked. This is the output from opera, FF gives nothing (yes, I did copy paste the code.):
```**** ACTION_MAP for fonts.googleapis.com
fonts.googleapis.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 0,
  "userAction": "user_allow"
}
**** SNITCH_MAP for fonts.googleapis.com

undefined```

**Comment by ghostwords** [comment]
Hmm, I'm not sure how your Badger got into this state for `fonts.googleapis.com` in Opera. What your output says is that you told Badger to allow `fonts.googleapis.com`, but it doesn't say anything about Badger ever learning to block `fonts.googleapis.com` ... Is this the complete output (looks like the "**** ACTION_MAP" line is cut off but is anything else missing)? Sorry, I don't know what's going on otherwise.

**Comment by ballsystemlord** [comment]
On Wed, 15 May 2019 11:38:47 -0700
Alexei <notifications@github.com> wrote:
> Hmm, I'm not sure how your Badger got into this state for
> `fonts.googleapis.com` in Opera. What your output says is that you told
> Badger to allow `fonts.googleapis.com`, but it doesn't say anything
> about Badger ever learning to block `fonts.googleapis.com` ... Is this
> the complete output (looks like the "**** ACTION_MAP" line is cut off
> but is anything else missing)? Sorry, I don't know what's going on
> otherwise.
>

I've tried to trigger this by going to the original URL and resetting PB.
I've tried resetting PB and then switching my customizations back on.
I've tried reseting PB changing my saved settings for
fonts.googleapis.com to blank and then importing my settings.

I can't trigger this any more.

As for the lines being cut off, no. That was all.

I guess this bug will just have to go into bit rot until someone else can
reproduce it.

My opera version, kernel version, etc. are all the same. Opera does
auto-update it's extensions though so perhaps this was a very temporary
glitch.

Thanks for your help in this.
