### ISSUE TITLE
flexible/quick update of MDFP

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#2395]
what do you think about making it possible to regularly update the MDFP instead of hardcoding it?

i know this is not ideal for privacy, but as [pinging a CDN already happens](https://www.eff.org/privacybadger/faq#Why-does-my-browser-connect-to-fastly.com-IP-addresses-on-startup-after-installing-Privacy-Badger) IMHO this would not be a big deal (concerning privacy).

**Comment by ghostwords** [comment]
Thanks for the suggestion! This came up before (#795). I think it makes some sense for MDFP, but I don't think we should work on this feature at this time.

I think the real problem is that we haven't had an update in several months now for various reasons. But we should be going back to a more regular (~monthly) schedule relatively soon.

**Comment by DJCrashdummy** [comment]
sorry for creating this duplicate! i was even wondering, why nobody already suggested this... but unfortunately i didn't find the "original issue". :slightly_frowning_face:

**Comment by ghostwords** [comment]
No problem, it's all good.

It's not that this isn't a good idea, it's that this will take some effort to do and we should probably devote the effort elsewhere.

**Comment by DJCrashdummy** [comment]
totally get it... that's why i wrote, that it *"would not be a big deal **(concerning privacy)**."* already in first place. :wink:
