### ISSUE TITLE
Privacy Badger decided to block the code.jquery.com domain

### ISSUE THREAD

**Issue by nvesely** [EFForg/privacybadger#2408]
Obviously, this is going to break a lot of sites. I don't manually block domains, so somehow its learning algorithm led to this. That should probably be fixed.

**Comment by ablanathtanalba** [comment]
Hi @nvesely, thanks for the comment. Have you encountered Privacy Badger breaking any sites because of this? It would help to know where, if so.

Currently `jquery.com` is an item in Privacy Badger's ["Yellow List"](https://github.com/EFForg/privacybadger/blob/master/doc/yellowlist-criteria.md) -- a custom list of domains from which Privacy Badger allows requests, but blocks them from certain tracking behaviors.

**Comment by ablanathtanalba** [comment]
Closing this issue for now, until any breakages occur

**Comment by ghostwords** [comment]
Hello @nvesely,

Could you provide the debug output for "jquery.com" by following the instructions in steps 2 and 3 of https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain?
