### ISSUE TITLE
Tracking domains list is hard to browse using scrollbar

### ISSUE THREAD

**Issue by personal-account-crypto** [EFForg/privacybadger#2422]
Firefox 68. List and scrollbar out of sync. Cannot reach end of list with scrollbar.

**Comment by ablanathtanalba** [comment]
Hello, thanks for reporting this issue. Just to make sure I'm correctly understanding the problem you're seeing -- you're saying that on the Tracking Domains tab of the Options page, you're currently unable to reach the end of the list by dragging the scroll bar to the end. 

If so, this is because the list of tracking domains is rendered in batches -- a common UI pattern when you're dealing with a very long list of items to speed up page load time. Each batch of domains is fetched and rendered as the scroll bar nears the end of the list, thus making the list longer and longer until you eventually reach the actual end. Once the entire set of domains is loaded, though, the scroll bar should behave as expected.

Please let me know if that's not what you're experiencing and we can investigate further.

**Comment by personal-account-crypto** [comment]
Seems you are on point.  Just to be sure I try to clarify: 
At that moment I had 1000-something entries in list. Dragging scrollbar "thumb" to the bottom end, only a first portion of list moved (100-200 who knows), so it could be what you refer as "batch".
In case I really needed to reach the end of "list" by the help of scrollbar, "thumb" must be dragged out of scrollbar bounds, and that could be take ages (not to mention cordination and acrobatics with mouse on the mousepad).

> ... a common UI pattern ...

dealing with scrolling and lists on a daily basis, never encountered such behaviour, so if you call this "common UI pattern", is it something about webextensions (or whatever the new format for Firefox addons is) ?

And one more thing regarding to "lists" (dont know if it should be separate issue or not) - take some random list long enough to be scrolled, find some "interesting" site and toggle the "red-yellow-green" bar. Now you are again at the top of the list and "scrolling fun" starts again.

**Comment by ghostwords** [comment]
Yep, the list is hard to scroll all the way through using the scrollbar. Is there a particular reason you are interesting in reviewing the complete list? I suggest using the search filter to narrow the list to particular domains you are interested in.

Privacy Badger is meant to be a no-configuration-necessary, install-and-forget kind of extension. Generally speaking, you should leave the sliders alone and let Privacy Badger do its job automatically.

Please subscribe to #1581 for the reset scroll bug.

**Comment by personal-account-crypto** [comment]
>  Is there a particular reason you are interesting in reviewing the complete list?

Yes, there is. Since you provided "user" with option to do that, I would like to examine "each and every" part. EFF WTF?

**Comment by ghostwords** [comment]
In any case, you can click on the list, and then use arrow or page up/down keys instead of the scrollbar.

**Comment by ghostwords** [comment]
This will be fixed in the Privacy Badger update. Sorry for all the crappy scrolling and thanks again for reporting!
