### ISSUE TITLE
Badge count fails to update upon navigating to homepage/new tab page

### ISSUE THREAD

**Issue by FudgeFury** [EFForg/privacybadger#2423]
Please look at the attached screenshots.

I have noticed that when I go into a website and then back to my default FireFox homepage, the tracker icon number bade does not update. If I open a new tab (I.E. start fresh), it goes back to its default state.

![1](https://user-images.githubusercontent.com/20489799/61891920-a2f0db80-af02-11e9-8c7a-01ffb5b3f672.png)
![2](https://user-images.githubusercontent.com/20489799/61891949-b439e800-af02-11e9-89ca-17f8ae5f2bb5.png)
![3](https://user-images.githubusercontent.com/20489799/61891957-b9973280-af02-11e9-9fe4-ff18ac9f437c.png)
![4](https://user-images.githubusercontent.com/20489799/61891959-bc922300-af02-11e9-9959-e6c16c800233.png)
![5](https://user-images.githubusercontent.com/20489799/61891961-bf8d1380-af02-11e9-9388-545df613652a.png)

**Comment by ghostwords** [comment]
Hello and thanks for the report! Just to be clear, this is all using the same tab in the same window, right? I can reproduce now in both Firefox and Chrome. Navigating back in history to the new tab page does not update the badge. Navigating back to a non-new tab page does seem to update the badge.

**Comment by FudgeFury** [comment]
Hello,

Yes, this is using the same tab in the same window. However I am not navigating back but instead pressing the home button beside the browser refresh.

I'm glad to be able to help in any way. This extension is slowly becoming my favourite
________________________________

**Comment by ghostwords** [comment]
Looks like tracker data shown in the popup (which comes from the `tabData` object) doesn't get updated either. So the underlying issue is probably that we reset `tabData` for a tab upon an `onBeforeRequest` event for the "main_frame" of the page, but we don't get this event for new tab pages (I think ... needs confirmation). This seems related to #1997/#2198.

**Comment by FudgeFury** [comment]
I'm not too good with developing so forgive my simple responses. Will there be a solution for it?
________________________________

**Comment by ghostwords** [comment]
Sure, once a Privacy Badger developer or a volunteer gets to working on this bug.

**Comment by ghostwords** [comment]
@ablanathtanalba We should probably fix this with a `chrome.webNavigation` listener that takes care of updating tab data.

The underlying problem here is that the way we reset tab data now (`chrome.webRequest.onBeforeRequest` with type `"main_frame"`) doesn't happen sometimes (when there is no actual Web request: going to an `about:`/`chrome:` page, returning to a Service Worker page that returns cached data, ...).

On the other hand, `chrome.webNavigation` should always fire upon navigation. One question is whether we will still need tab data resetting upon `onBeforeRequest`/"main_frame", but we should be able to answer that experimentally.
