### ISSUE TITLE
Is Firefox tracking protection done after privacybadger?

### ISSUE THREAD

**Issue by SuffolkPunch** [EFForg/privacybadger#2487]
I'm running PrivacyBadger v 2019.10.8 in Firefox v 70.0.
Issue: When a web page is loaded is PB applied to its content before or after FF Enhanced tracking Protection blocks trackers?  From a few tests is looks as if PB's applied first. 

Perhaps, off topic, but I'll ask on case there's a generally applicable answer: What determines the order add-ons like Noscript, DuckDuckGo Privacy Essentials, Privacy badger and FF Enhanced Tracking Protection get applied?

**Comment by ghostwords** [comment]
Good question! I'm guessing it's the order in which your add-ons were installed. I opened a [Mozilla Bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1591576) to confirm.

**Comment by ghostwords** [comment]
According to answers on Bugzilla, add-on request handling order is not defined by anything intentionally, so you can't rely it to be a certain way, or to stay the same.

As for ETP ... it's not clear! Mozilla employees suggest ETP happens first, while experimentation seems to show (or at least showed) that add-ons can successfully redirect resources that would otherwise have gotten blocked by ETP. So, which is it?

I suggest continuing [this conversation on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1591576).
