### ISSUE TITLE
google.* and link blanker extension

### ISSUE THREAD

**Issue by urfausto** [EFForg/privacybadger#2543]
Hi, since i've installed this extension the behaviour of tabs opening on google.* went broken.
i use link blanker to automatically open links in a new tab (https://chrome.google.com/webstore/detail/link-blanker/lkafdfakakndhpcpccjnclopfncckhfn).
disabling this extension makes the behaviour become normal again, but upon activating it reappears.
in short what happens is that it does not let me anymore open links in new tabs as instructed by the link blanker but will open them in the current tab instead.
it is weird because on other sites everything seems to work normally.

**Comment by urfausto** [comment]
i'm on vivaldi browser (chromium) x64, latest release.

**Comment by ghostwords** [comment]
Sounds like this may be caused somehow by Privacy Badger's [Google link tracking protection](https://www.eff.org/deeplinks/2018/10/privacy-badger-now-fights-more-sneaky-google-tracking) (as that protection is [only active on google.com domains](https://github.com/EFForg/privacybadger/blob/40ff7546941da2e355c1a03f8a0303232c9b70fc/src/manifest.json#L71-L77)).

@ablanathtanalba Could you take a look?

**Comment by ablanathtanalba** [comment]
This is indeed caused by the link tracking protection that Privacy Badger offers, specifically at these [two lines in the code where Privacy Badger blocks event listeners on links in a google domain](https://github.com/EFForg/privacybadger/blob/65f381acbf2e2ade7abfe1a450fd1d1228840944/src/js/firstparties/google-search.js#L23). I suspect that the Link Blanker extension adds event listeners on all links, so it only applies the `target=__blank` attribute to a link when the `click` or `mousedown` event fires.

Since the attributes on google links are still being pared down to only the bare essentials, I think that link tracking protection would still be effective without those two lines, though I'll need to do some more research to confirm. If that's the case, [this PR will take care of it](https://github.com/EFForg/privacybadger/pull/2595).

**Comment by ablanathtanalba** [comment]
An update to the experiments I tried in #2595 : The two lines of code that cause this breakage are also needed to prevent outgoing link tracking protection on google search results pages. As far as I was able to find, there isn't a way to pass exception to the code run by LinkBlanker while also preventing the tracking Google does on those links. I'll keep an eye on the behavior of those search results links to see if anything changes there that would allow us to solve this issue.
