### ISSUE TITLE
Consolidate user blocking lists for DNS filtering? Make a spider with the badger's heuristics?

### ISSUE THREAD

**Issue by moodule** [EFForg/privacybadger#2555]
Hello, I love what you're doing here ! :+1:

I also started filtering at the source via the [Pi-Hole](https://pi-hole.net/), and I merge my badger's blocking list with its hosts file.
Of course my own list is limited, while as a community the badger's users have explored much more of the web.

So why not consolidate the lists of volunteering users and make a central blocking list?
With a button to opt-in your personal blocking list for example?

I know it looks suspicious for user privacy once again, is it the reason you don't propose this option?

Or what would you think of a spider running the badger's heuristics and indexing scammy websites all-day long?

**Comment by ablanathtanalba** [comment]
Hi @moodule, thanks for the support and reaching out. It sounds like you'd probably be interested in another EFF project: [badger-sett](https://github.com/EFForg/badger-sett). It's an automated crawler we use to pretrain new instances of privacy badger, using the same heuristics. While still fairly new, it's something we're continuing to work on so that it's even more robust and valuable. Please feel free to download it and run your own scans!

What sets privacy badger apart from other tracker blockers right now is that each installation becomes uniquely tailored to the user over time. This keeps it lightweight while still "intelligent", learning to block new trackers by identifying tracking behavior rather than relying on a set list. An opt-in model for users to share their lists is a compelling idea, but I worry it would raise privacy flags you brought up. That, and we want to keep privacy badger as simple as possible for everyday less-technical users to install and forget about it.

**Comment by moodule** [comment]
This is 100% great I really love it!! It makes a lot of sense too, and the badger does an outstanding job at being low-key (and nothing broken yet!).
Now I'm thinking the opposite: use the current blocking list as training / testing for the badger.
May-be in a deep-learning style idk?

Thank you very much for answering! :ok_hand:
I'll go to [badger-sett](https://github.com/EFForg/badger-sett) and contribute :)

Btw: was it the right place to ask???
I'm always surprised to get such detailed answers volunteered!! :heart:

**Comment by ghostwords** [comment]
Previous discussion: #1299.

**Comment by ablanathtanalba** [comment]
@moodule this is definitely the right place to ask -- we appreciate it when folks reach out with their ideas! Definitely take a look at badger-sett and please feel free to contribute there, ask questions, etc
