### ISSUE TITLE
Firefox, Windows: no icon next to URL bar or in overflow menu

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [EFForg/privacybadger#2625]
Upon installing the extension, no icon for it shows anywhere.

The AddOn does appear on `about:addons` (although, initially - before uninstalling, reinstalling, and cleaning up my browser profile a bit - it did not appear there).

Uninstalling and reinstalling does not fix the missing icon.

The problem might lie in my profile but I'd rather not 'refresh' the profile. As said above I did clean the profile somewhat. I did so by removing directories for AddOns that I no longer had installed.

Windows 10 1909
Firefox 77.0.1 x64
Privacy Badger 2020.6.2

EDITED.

**Comment by ghostwords** [comment]
OK thank you, sounds like uninstalling and reinstalling Privacy Badger worked around the Firefox bug for now.

Let me know if the problem comes back. We should then get the relevant error message from Privacy Badger's [background page console](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain#2-open-privacy-badgers-extension-background-page). This seems to be some sort of Firefox bug, but it's not yet clear what it is.

**Comment by ghostwords** [comment]
Going by a support email from September 2019, the error message may be `No WebExtension found with ID jid1-MnnxcxisBPnSXQ@jetpack` (coming from `ExtensionParent.jsm:706`).

**Comment by LinuxOnTheDesktop** [comment]
I have edited my original post to add a 'not' that had gone missing. The case of the missing icon does persist. Here is what I see in 'Privacy Badger's background page console.'

![image](https://user-images.githubusercontent.com/47056543/84174171-c4e94300-aa6d-11ea-92ac-0a3652228d0e.png)

**Comment by ghostwords** [comment]
What happens when you visit Privacy Badger's options page? Is it blank or does it display correctly? If it is blank, what does the JavaScript console for the options page show?

What happens when you right click on the Firefox toolbar and select Customize? Is the Privacy Badger icon on the Customize screen somewhere? If it is, you can then drag it to the toolbar.

**Comment by LinuxOnTheDesktop** [comment]
> What happens when you visit Privacy Badger's options page? Is it blank or does it display correctly?

It displays correctly.

> Is the Privacy Badger icon on the Customize screen somewhere? If it is, you can then drag it to the toolbar.

It was. So I did. Thank you. User error? Or should reinstalling the addOn unhide its icon?

**Comment by ghostwords** [comment]
OK great, thank you, glad we figured this out. I don't know offhand how Firefox handles extension settings/icon placement when reinstalling, but whatever Firefox does is not specific to Privacy Badger.
