### ISSUE TITLE
Blocks FastSpring script

### ISSUE THREAD

**Issue by rilwis** [EFForg/privacybadger#2694]
Hi,

I'm using [FastSpring](https://fastspring.com), an e-commerce platform. It adds a script to [my website](https://metabox.io) to allows users to make payments without living the website. You can see it in action on [my pricing page](https://metabox.io/pricing/).

However, when Privacy Badger is enabled, the FastSpring script is blocked and not run. Thus, users can't make the purchase.

As FastSpring is not an ads, trackers, please remove it from the block list so users can make payments.

Thanks,
Anh

**Comment by ghostwords** [comment]
Hello!

Instead of keeping lists of what to block, Privacy Badger [automatically learns to block trackers](https://privacybadger.org/#How-does-Privacy-Badger-work).

Does moving the slider to "yellow" (block cookies) for any `onfastspring.com` domains on your site, and reloading the page work around the problem?

Could you provide the [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "fastspring"?

**Comment by ghostwords** [comment]
Let me know if you have more information.
