### ISSUE TITLE
Understanding the user data json file 

### ISSUE THREAD

**Issue by aryan096** [EFForg/privacybadger#2716]
Hello! 

I am a student working with privacy badger user downloadable data for a project. I needed to understand what the json file represents and couldn't find any information online. Could someone explain what action_map, settings_map, and snitch_map store?

**Comment by ghostwords** [comment]
Hello!

I just updated our [design document](https://github.com/EFForg/privacybadger/blob/master/doc/DESIGN-AND-ROADMAP.md) to explain `action_map` and `snitch_map` (under Further Details).

As for `settings_map`, it contains various [Privacy Badger settings](https://github.com/EFForg/privacybadger/blob/e4f19007ca2b61b69abd922c0ba450ea6744c858/src/js/background.js#L755-L777), both internal (`seenComic` stores whether the user interacted with the new user welcome page already) and user-facing (typically available on the options page).

Let me know if you have any questions.

**Comment by aryan096** [comment]
Hi! Thank you for the update! I had a quick question, is the info stored in the snitch_map based on the user's activity? It seems to store data about websites that I have never visited. For example, the domain value that occurs the most is informationweek.com, a website I haven't visited.

**Comment by ghostwords** [comment]
[Privacy Badger includes pre-trained tracker data](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start) gathered by [Badger Sett](https://github.com/EFForg/badger-sett). If you then enable local learning in options, your Privacy Badger will build on that pre-trained data as you browse the Web. You can clear the pre-trained data under the Manage Data tab on the options page.

**Comment by ghostwords** [comment]
By the way, there are a few problems with using a stock Privacy Badger to answer questions like which websites have the most trackers.

For example, trackers often load other trackers dynamically. When a tracker that brings in other trackers is blocked, Privacy Badger never sees the trackers that would have been loaded otherwise.

Moreover, `snitch_map` records up to three sites per tracker only.

So if you want to use Privacy Badger to figure out which sites have the most trackers, which trackers appear on the most sites, etc., you should use a modified Privacy Badger, one that doesn't block (or modify in any way?) requests, and one that doesn't cap `snitch_map` entries to three sites.

**Comment by aryan096** [comment]
That is really helpful, thank you! I have been looking at the code to figure out how to remove the three sites cap on snitch_map entries, but couldn't really find how to do that. Do you have any suggestions?
Also, if blocking is entirely disabled, do you think the dynamically loaded trackers problem be solved?

**Comment by ghostwords** [comment]
I think your best bet is to set `TRACKING_THRESHOLD` to a high number so that Privacy Badger effectively never decides to block anything. This should take care of both `snitch_map` (capped to `TRACKING_THRESHOLD`), and no longer blocking ("red" slider) nor modifying any requests/denying JS storage access ("yellow" slider).

Don't forget to enable local learning (under General Settings > Advanced) and clear all pre-trained data (under the Manage Data tab).

You may also want to disable sending "Global Privacy Control" and "Do Not Track" signals (under General Setttings), as some websites do respect them and serve fewer or no trackers in response.

**Comment by aryan096** [comment]
Gotcha! Thank you so much. From there, the process to install this modified version should just be to create an xpi file using the manifest.json? (I have no experience with extensions haha)

**Comment by aryan096** [comment]
Hey! So it seems like raising the threshold doesn't actually do anything. PB still blocks trackers after 3 spots. I commented out the code from line 331-335 in heuristicblocking.js and nothing changed. Do you have any more pointers?

**Comment by ghostwords** [comment]
Did you update [`TRACKING_THRESHOLD`](https://github.com/EFForg/privacybadger/blob/03718e91f4a2d798c35ab119e7344fcb2acf2e37/src/js/constants.js#L40) to let's say `3000000` and then [reload the unpacked extension](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/#reloading-a-temporary-extension)? You have to reload the extension after every code change you make, or your changes do not get applied.

**Comment by aryan096** [comment]
I did. I am using Chrome, and I load the src everytime I change something. I can try Firefox to see if that is any different.

**Comment by ghostwords** [comment]
The browser shouldn't make a difference. I think there is something off with your workflow. Did you clear the pre-trained data, for example?

If you're still having trouble, post the exact steps you followed and we could go from there. For example:

1. `git clone https://github.com/EFForg/privacybadger.git`
2. Edited `constants.js` to set `TRACKING_THRESHOLD` to `300`
3. Loaded the unpacked extension into Chrome
4. Clicked "Remove all" under Manage Data on the options page
...

**Comment by aryan096** [comment]
This is probably the silliest mistake I have made. I had a packed release of PB installed on Chrome, which was overriding the unpacked one I installed. It works as intended now. Thank you, and sorry for the confusion!!
