### ISSUE TITLE
Show domains that don't appear to be tracking you

### ISSUE THREAD

**Issue by iamlukeallen** [EFForg/privacybadger#2734]
Hi, i'll be brief as I don't know if this is the place to ask this.

**"Show domains that don't appear to be tracking you"**
Can this option be enabled without the learning being enabled. I like the ability to see which domains are being connected to, even those that do not appear to be tracking me.

PS. I love this project.

**Comment by ghostwords** [comment]
Hello, thank you, and great question!

The short answer is that you have to enable local learning in order to have the option to see non-tracking domains at this time.

Privacy Badger sorts third-party domains into three types:
- Domains that Privacy Badger already learned to (cookie)block
- Domains that Privacy Badger hasn't yet decided to block (because they haven't yet been seen tracking on enough sites)
- Domains that haven't been seen tracking at all yet

By default, [local learning is disabled](https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better), and we only show domains that Privacy Badger actually did something about: blocked or "cookieblocked" (for "yellowlisted" domains). It doesn't seem to make sense to show hasn't-yet-decided-to-block domains as they will not automatically change status, at least not until a Privacy Badger update with a newly [pre-trained set of domains](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start). Furthermore, Privacy Badger is meant to be mostly a hands-off, install-and-forget tool. It's easy to break the Web for yourself by moving sliders for just a couple of domains (#2021).

If you choose to enable local learning, we automatically start showing domains that Privacy Badger hasn't yet decided to block, as they now could actually become automatically blocked in the future. As you are an advanced user, you also get the option to see domains that haven't been seen tracking at all. I see this as a feature useful mostly to Privacy Badger developers.

It doesn't seem to make sense to offer the option to see non-tracking domains without also showing hasn't-yet-decided-to-block domains. I suppose we could make it so that enabling this option will show all domains, hasn't-yet-decided and non-tracking both. But I'm still not clear on who this feature is for; why would you keep learning off but want to be more hands-on with domains?

If you're looking for more manual control over what is and isn't allowed to load, I suggest installing another tool (like uBlock Origin) that is specifically built for this use case.

Let me know what you think. We're beginning work on simplifying the popup UI where instead of the list of domains, by default we show a summary of what happened and a "show more" link. Perhaps this will let us get rid of the "Show domains that don't appear to be tracking you" option entirely (added in #2359 to help users avoid breaking the Web for themselves), and just always show all three types of third-party domains once you've elected to see more.

**Comment by iamlukeallen** [comment]
That actually makes a lot of sense. I'll be honest, it was a question of curiosity for how it worked more than anything. I understand that it is designed to be user friendly, and "hide" the potentially harmful options - I think that is a good choice overall as like you said, makes it a set and forget extension which it is fantastic for.

I guess I have nothing really left to add, thank you for taking the time to reply to me.

Is there a downside to me enabling the learning again? I read the article explaining how it could potentially be used for fingerprinting but if you dont mind answering, how likely is that out in the wild?

**Comment by ghostwords** [comment]
>Is there a downside to me enabling the learning again? I read the article explaining how it could potentially be used for fingerprinting but if you dont mind answering, how likely is that out in the wild?

I don't think it's likely because of how both limited and cumbersome it is. I don't have much to add to what we wrote in the "Why is local learning still an option?" section of the [aforementioned article](https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better).

**Comment by ghostwords** [comment]
We would have removed local learning entirely if we thought the risks outweighed the benefits.

**Comment by ghostwords** [comment]
Let me know if you have any other questions or feedback.
