### ISSUE TITLE
Update README and docs to reflect disabling of local learning

### ISSUE THREAD

**Issue by jscott0** [EFForg/privacybadger#2735]
Hi,
I'm taking over the Debian package and am having trouble finding inspiration for what to put in the package description, since the README and privacybadger.org are now out-of-date with respect to local learning. In particular I'm looking for a satisfying answer for what does or will set Privacy Badger apart.

I'm hesitant to specify that one even _may_ opt into learning, since that may seem like an endorsement for enabling. If it's felt that the docs are still accurate with the community learning draft, I could retain the existing description.

**Comment by ghostwords** [comment]
Please use the language from the README. Privacy Badger is still a browser extension that automatically learns to block invisible trackers. It is still the case that instead of keeping lists of what to block, Privacy Badger automatically discovers trackers based on their behavior.

Users may opt into local learning or not, but whether you do or not doesn't change what Privacy Badger is and what sets it apart. There is still automatic learning, and we still do not curate manual block lists.

Let me know if you have any questions.

**Comment by ghostwords** [comment]
In fact, if you felt the need to amend the README in any non-trivial way, I would love to discuss it here first. Privacy Badger's description should be consistent across all distribution channels; if there is a problem, we should fix it everywhere.

**Comment by jscott0** [comment]
I'll keep it as-is; I hadn't realized that there was still learning going on, and I see that's not going to change. Thanks for your timely response.
