### ISSUE TITLE
"Something went wrong." on Twitter when using redirect

### ISSUE THREAD

**Issue by bersbersbers** [EFForg/privacybadger#2737]
#### What is your browser and browser version?
Chrome 88

#### What is broken and where?
The link https://s2.washingtonpost.com/2e46378/ redirects to https://twitter.com/AnimalsWorId/status/1347212769716629505?s=20&=

While the latter works, the former results in "Something went wrong." *if already logged into Twitter*.

#### What is the "culprit" domain?
twitter.com

#### What is your debug output for this domain?
```
**** ACTION_MAP for twitter.com
platform.twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
syndication.twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
twitter.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
**** SNITCH_MAP for twitter.com
twitter.com [
  "linkedin.com",
  "amazon.com",
  "adobe.com"
]

```
![image](https://user-images.githubusercontent.com/12128514/106094848-06c91580-6133-11eb-8137-284d5da16548.png)

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

I see these "Something went wrong" messages all the time myself, with or without using Privacy Badger. Reloading the Twitter page once or twice fixes them. Are you sure Privacy Badger is at fault?

What does Privacy Badger report as blocked on the page when this happens? Can you reproduce if Privacy Badger is disabled on Twitter? Can you reproduce if Privacy Badger is disabled globally (by toggling the switch for Privacy Badger on `chrome://extensions/`)?

**Comment by ghostwords** [comment]
I think I see what's going on. This looks like the same bug as https://github.com/EFForg/privacybadger/issues/2706#issuecomment-729118487.

Because `https://s2.washingtonpost.com/2e46378/` is a 302 redirect and because Twitter uses Service Workers, Privacy Badger gets confused (when the Service Worker for Twitter has already gotten cached in your browser) and acts like it's still on `s2.washingtonpost.com` when it's actually on Twitter. This results in Privacy Badger blocking cookies for `twitter.com` (instead of ignoring `twitter.com` resources as first party, as Privacy Badger should), which results in the "Something went wrong" error when you're signed into Twitter.

**Comment by ghostwords** [comment]
Until we figure out a way to deal with the underlying issue in Privacy Badger, you should be able to work around this error on Twitter by reloading the page once or twice.

Alternatively, if this always happens when following Twitter links from the Washington Post, you could add `s2.washingtonpost.com` to Privacy Badger's list of disabled sites (visit the Disabled Sites tab on Privacy Badger's options page).

**Comment by bersbersbers** [comment]
For the record:
> Are you sure Privacy Badger is at fault?

Yes

> Can you reproduce if Privacy Badger is disabled on Twitter? 

No

> Can you reproduce if Privacy Badger is disabled globally (by toggling the switch for Privacy Badger on chrome://extensions/)?

Yes

Otherwise, thanks for the explanation and sorry for the duplicate. I'll follow #2706, feel free to close this.
