### ISSUE TITLE
Could Privacy Badger integrate some features of Privacy Possum? 

### ISSUE THREAD

**Issue by 0x391F** [EFForg/privacybadger#2761]
Privacy Possum's (PP) on Github
https://github.com/cowlicks/privacypossum

PP seems doen't maintiance anymore, and it sometimes break some webpages. 

Some important features of PP: 

- Inject random data to spoil the first party fingerprint
- Etag blocking
- Referer headers blocking

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

- Regarding fingerprinting defenses, please see the discussion in #2567. The gist is that this is something best left to the browser.
- For ETags, please subscribe to #2136 for updates.
- Browsers at this point default to some version of the `strict-origin-when-cross-origin` referrer policy, which means cross-origin requests receive only origins instead of full URLs. Privacy Badger also enforces origin-only referrers for all cookieblocked requests (#2505). I'm not sure doing more makes sense, as blocking referrer headers entirely tends to break sites ([some examples](https://github.com/EFForg/privacybadger/pull/2155#issuecomment-442550282)). We could look into enforcing origin-only referrers for all third-party requests (and further trimming cookieblocked request referrers to eTLD+1), to emulate [Safari's behavior](https://github.com/privacycg/proposals/issues/13#issue-609229861) in all browsers.

Let me know if you have any questions.
