### ISSUE TITLE
Apple Music embeds aren't blocked?

### ISSUE THREAD

**Issue by clasick** [EFForg/privacybadger#2778]
I see that Privacy Badger automatically blocks Spotify embeds and Soundclouds embeds with a widget replacement. Why isn't the same thing done for Apple Music embeds? You can find both of these side by side on this page: https://www.npr.org/2021/02/09/965903895/new-music-friday-the-top-8-albums-out-on-feb-12 . Is it because Apple Music isn't tracking user data or something else?

**Comment by ghostwords** [comment]
Hi and thanks for getting in touch!

I just opened a PR (#2779) to add a placeholder for Apple Music embeds so that Privacy Badger knows how to replace them after the next update.

However, since `apple.com` is on the yellowlist, rather than blocking Apple embeds entirely, Privacy Badger will only block access to cookies and will not replace their HTML elements.

I need to review what else `apple.com` is used for in third-party contexts, and I need to make sure all of our replacement placeholders (such as the Apple Music placeholder) have been released to Privacy Badger users before I can remove `apple.com` from the yellowlist.

Once you get the next Privacy Badger update, you can move the slider for `apple.com` to "red" for yourself to start fully blocking Apple embeds and to start seeing our placeholders in their place.

Let me know if you have any questions.

**Comment by clasick** [comment]
@ghostwords Got it, thanks for the quick patch! Will test it after the next release for sure.
