### ISSUE TITLE
Block https://metricsflow.com/

### ISSUE THREAD

**Issue by ramonsmits** [EFForg/privacybadger#2829]
It seems privacy badger isn't blocking https://metricsflow.com/ what it the policy to get this blocked?

**Comment by ghostwords** [comment]
Hello!

Just to be clear, there is no manually-assembled block list in Privacy Badger; [Privacy Badger automatically learns](https://privacybadger.org/#How-does-Privacy-Badger-work) to block trackers by observing their behavior.

The `metricsflow.com` hasn't yet been observed in [pre-training](https://github.com/EFForg/badger-sett), which is why Privacy Badger doesn't yet know about it out of the box. We are steadily expanding the reach of pre-training scans, which means Privacy Badger should eventually learn to block `metricsflow.com` by default.

If you enable local learning, your Privacy Badger should be able to learn to block `metricsflow.com` automatically. You could also move the slider for the domain to "red" yourself, if you wish.

Let me know if you have any questions.
