### ISSUE TITLE
No Youtube widget on Aljazeera.com

### ISSUE THREAD

**Issue by etanot** [EFForg/privacybadger#2849]
**Type:** Bug report

#### Description
When **youtube.com** domain is blocked (i.e. PB's slider is at left hand side), there is no Youtube widget for videos which are hosted on Youtube.

#### Steps to reproduce
- Find any web page which embedded a Youtube hosted video on Aljazeera.com. For example, go to [Dear Future Children: A new generation of activism](https://www.aljazeera.com/program/witness/2022/8/10/dear-future-children-a-new-generation-of-activism) documentary page.
- Move the slider for **youtube.com** domain to the left hand side to block the domain.
- Now reload the page to reflect the changes.

#### Expected behavior
Video's placeholder should be replaced with PB's Youtube widget.

#### Actual behavior
A blank (/black) screen is present at video's placeholder.

![aljazeera](https://user-images.githubusercontent.com/28824347/187065188-977cad9b-f217-4961-9734-7224ca9b7d8c.png)

#### What is your browser and PB version?
Browser: Mozilla Firefox, 91.13.0esr (64-bit)
PB: 2021.11.23.1

**Comment by ghostwords** [comment]
Hello and thank you for the report!

Looks like the site uses the YouTube API (rather than embedding YouTube in an iframe) to initialize the YouTube player. At this time Privacy Badger only supports replacing YouTube iframes.

This will be fixed when we implement a more complete [surrogate-based replacement](https://github.com/EFForg/privacybadger/pull/2805) for YouTube. We should then be able to [remove YouTube domains from the yellowlist](https://github.com/EFForg/privacybadger/issues/1593) to offer blocking with replacement by default to all Privacy Badger users.

**Comment by ghostwords** [comment]
Hi @etanot, this should be fixed in Privacy Badger version 2022.9.27. Thanks again for the report! I'm very interested in improving and expanding our widget replacement system.
