### ISSUE TITLE
Implement prefers-color-scheme:dark for replacement-widget

### ISSUE THREAD

**Issue by imme-emosol** [EFForg/privacybadger#2862]
In #2732 privacy badger has been made available in a dark theme.
The widget replacement has not yet been implemented as such.

It seems related to the colors in this piece of code:
https://github.com/EFForg/privacybadger/blob/eb077923b06aaf347092385a8151190f2b3b30ae/src/js/contentscripts/socialwidgets.js#L440

As a rather random side-note: why is all that ` !important` used?

**Comment by ghostwords** [comment]
Hello and thanks for opening this issue!

Should our widget placeholders follow the rest of the extension/browser UI in using dark/light mode, or should the placeholders try to match the mode of the page they are on?

The `!important` is there because our widget placeholders are not yet attached to (closed root) shadow DOM, but page DOM directly. This means pages can potentially override placeholder styles, and so we need [all sorts of workarounds](https://github.com/EFForg/privacybadger/blob/eb077923b06aaf347092385a8151190f2b3b30ae/src/js/contentscripts/socialwidgets.js#L449) (such as `!important` on all styles) to try to prevent this from happening.

**Comment by imme-emosol** [comment]
> Should our widget placeholders follow the rest of the extension/browser UI in using dark/light mode, or should the placeholders try to match the mode of the page they are on?

The (display-/theme-)mode of the page (a widget placeholder is on) might be implemented in all sorts of ways.

As far as i can predict, the go-to direction for these matters are the "new" css-media-queries/-features, and I expect all websitedevelopers to (slowly but surely) move into that direction (prefers-color-scheme, prefers-contrast, prefers-reduced-motion).

Added to that, I would like to add that a dark, well contrasted theme will be less likely to cause eye-strain, in contrast to a light theme.

Taking the above into account, I arrive at the idea that privacybadger's widget placeholders should follow the rest of the extension/browser-UI (as websites should).

Regarding the `!important`, the widget placeholders should/will be moved into the (closed root) shadow DOM?

**Comment by ghostwords** [comment]
Widget replacement placeholders will support your browser's dark mode in the next Privacy Badger update.

Thanks again for opening this issue, and let me know if you run into any problems!

>Regarding the !important, the widget placeholders should/will be moved into the (closed root) shadow DOM?

Yes, exactly, this should happen at some point.
