### ISSUE TITLE
Google search link unwrapping doesn't work on image search results

### ISSUE THREAD

**Issue by hyder365** [EFForg/privacybadger#2866]
When on a google search result page, right-clicking the true URL to copy it now gives me the google tracking url again instead. Privacy Badger used to fix this and is one of its best features. It would be great if it could be fixed again. I'm using PB on Firefox.

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

I wasn't yet able to reproduce this problem. If I disable Privacy Badger for google.com, I do see that right-clicking on a search result and copying the link to clipboard produces Google-wrapped links, but not when Privacy Badger is enabled.

- Is Privacy Badger enabled on the search results page?
- Does this happen for all searches or only some?
- Are you signed into your Google account? If yes, can you reproduce after signing out?
- Can you reproduce if you disable all other extensions and reload the search results page?
- Can you reproduce if you [install Privacy Badger](https://privacybadger.org/) in a [new Firefox profile](https://support.mozilla.org/en-US/questions/1262935)?

**Comment by hyder365** [comment]
After a little more testing, it seems to work fine on normal google search results (both logged in and not) but it stops working for google image search results.

I click on one of the images and get the title (and link) to the article under the image, as well as a "visit" button with the same link. Hovering over either the title or the "visit" button shows the same real URL, but clicking or right clicking on it reverts ti back to the one with tracking.

**Comment by ghostwords** [comment]
It looks like Google image search result links work differently from Google text search results in both Firefox and Chrome. Instead of being wrapped from the start, the links become wrapped (in the same way/format in both browsers?) on (right-)click. Furthermore, image result wrapped links use a different format ('https://www.google.com/url?` vs. '/url?`) from text result links.

Another difference between text and image search result pages is that image search results are generated dynamically rather than all at once, and keep being generated on scroll.

This suggests we should update the [Google search link unwrapping script](https://github.com/EFForg/privacybadger/blob/master/src/js/firstparties/google-search.js) to work more like the [Facebook unwrapping script](https://github.com/EFForg/privacybadger/blob/master/src/js/firstparties/facebook.js) and use a `MutationObserver` to respond to dynamic DOM changes. We also need to detect the slightly different wrapped link format.

**Comment by ghostwords** [comment]
We have a similar issue with [our other Google link unwrapper script](https://github.com/EFForg/privacybadger/blob/master/src/js/firstparties/google-static.js) where we fail to unwrap links in Google Docs/Sheets added after the page's initial load, such as during document editing.
