### ISSUE TITLE
Privacy badger not initializing on Youtube

### ISSUE THREAD

**Issue by ArbortPrinciples** [EFForg/privacybadger#2973]
Privacy badger is not working on Youtube.

OS: Windows 10
Privacy badger version: 2024.5.31

![image](https://github.com/EFForg/privacybadger/assets/117398158/4d328f53-165d-4b6a-a929-1b23e07dd4a7)

**Comment by ghostwords** [comment]
Hello! This will be fixed in Privacy Badger version 2024.6.3, currently pending Mozilla review.

In the meantime, it should help to restart Privacy Badger. To do so, visit your browser's extensions management page and toggle Privacy Badger off and then back on.

Let me know if you have any questions.
