### ISSUE TITLE
Add uninstall page for user feedback and retention

### ISSUE THREAD

**Issue by lenacohen** [EFForg/privacybadger#2985]
Most popular extensions have a page that opens on uninstall and asks users why they uninstalled. We should create an uninstall page that opens when users uninstall Privacy Badger. This page could:

- Collect Feedback: Allow users to explain why they are uninstalling, helping us identify areas for improvement.
- Clarify Misconceptions: Remind users that they can disable Privacy Badger on specific sites, in case they are uninstalling because of a broken site.
- Provide Reinstallation Option: Include a button linking back to the installation page.

An uninstall page can help us increase retention. To reduce uninstalls, we need to understand why users are uninstalling. Feedback from users who uninstall can provide insights to improve the experience for all Privacy Badger users.

**Comment by ghostwords** [comment]
I'm leaning towards "wontfix" for this mainly because the uninstall feedback page has to live on a remote server. Opening a tab is annoying enough already but opening a tab to our website is/can be seen as a privacy intrusion. We should strive to positively surprise our users. However, an uninstall feedback page will be perceived as a negative surprise, at least by some users.

My sense about the benefits of this feature is that we already have plenty of feedback for where we need to do better. I also think that we won't reach many people who got to the point of wanting to get rid of PB. It's possible they will reinstall us later, but I don't think popping a tab will help that. Just think of when you click unsubscribe links in mailing lists, and the mailing list has a form that wants your feedback. My one reaction there is, did I actually get unsubscribed or what? I am not giving this form a second more of my time than I need to. That's what I think most people have been trained to do.

**Comment by lenacohen** [comment]
I agree that this is low priority, but could we keep this issue open as a future possibility? 

While I understand that it could be implemented in a privacy-intruding way, I don't think it has to be. We already open a tab automatically on first run, collect opt-in feedback through the error reporting form, and link to our privacybadger.org site in several parts of the popup.

Most importantly, an uninstall page would provide feedback that we don't get from other channels. First, it would reach people who don't open GitHub issues or know how to use the popup to report an issue. Second, a multiple-choice survey listing common problems or misconceptions about Privacy Badger would provide feedback in a more actionable format. The percentage of respondents choosing each issue would help us understand and prioritize interventions. This feedback would not only help prioritize issues to solve but also help us measure the effectiveness of our interventions. For example, if 20% of respondents uninstall because they "didn't understand how to use it," we could gauge the effectiveness of changes to the popup or first-run page by observing how that percentage changes after the intervention. Error reports may not capture the same user group or address the full range of issues that users experience with Privacy Badger.

Before pursuing this, we could reach out to other privacy extensions with uninstall pages and ask about their response rates. While it may ultimately not be worth implementing, I think we should keep it on the table.

**Comment by ghostwords** [comment]
> We already open a tab automatically on first run

The welcome page is a local extension page. Not unexpected website connection made. The opt-in feedback form is opt-in, the links are things you can choose to click or not. An uninstall page is opening a tab to a remote website.
