### ISSUE TITLE
Privacy Badger is now blocking Microsoft Edge from translating a page

### ISSUE THREAD

**Issue by nickchomey** [EFForg/privacybadger#3014]
Recently I noticed that the page translation mechanism in Edge was no longer working. I finally traced it to Privacy Badger. Translation works when Privacy Badger is turned off, but not when it is on. 

![image](https://github.com/user-attachments/assets/cc934a46-d103-4a2d-8dba-492507836919)

I've tried this on Edge Beta and Edge Dev.

I've tried adding the domain (`edge.microsoft.com` from `https://edge.microsoft.com/translate/translatetext?from=de&to=en`) to the Disabled Sites list, but it doesn't help. I can't really live without both of these tools, so I hope this can get fixed.

**Comment by ghostwords** [comment]
Hello and thanks for opening an issue!

This is another breakage caused by #2968.

The Disabled Sites tab is for turning off Privacy Badger on a website. You could try visiting the Tracking Domains tab instead, searching for `edge.microsoft.com`, and then moving the toggle to the middle, yellow position. Let me know if that helps.

Another workaround is to replace the Privacy Badger you installed from [Chrome Web Store](https://chromewebstore.google.com/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) with the Privacy Badger from the [Edge add-ons store](https://microsoftedge.microsoft.com/addons/detail/privacy-badger/mkejgcgkdlddbggjhhflekkondicpnop). We plan on keeping Privacy Badger for Edge on Manifest V2 for as long as possible.
