### ISSUE TITLE
Enhancement: Block or Flag Non-ASCII domain names

### ISSUE THREAD

**Issue by TurtleEngr** [EFForg/privacybadger#3035]
This would help prevent: "Phishing with Unicode Domains" that look OK.
https://www.xudongz.com/blog/2017/idn-phishing/

**Comment by ghostwords** [comment]
Hello and thank you for the suggestion!

This seems like it would be a security and not at all a privacy feature. As such, it doesn't seem like a good fit for Privacy Badger. It doesn't mean it's not a worthwhile idea to pursue, it's just that since we have limited resources, we have to be selective about which ideas we pursue. Let me know if you have any questions or followup thoughts. Thanks again!
