### ISSUE TITLE
Adblocker blocker on www.sueddeutsche.de

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadger#494]
I don't know which tracker is the issue but when I visit http://www.sueddeutsche.de/politik/neue-wikileaks-dokumente-wie-die-nsa-das-auswaertige-amt-ausforschte-1.2575022 I can't click on anything in the "header" like the home symbol, Politik, Wirtschaft, ...
When I disable PB everything's fine again.

**Comment by rvaneijk** [comment]
It may have to do with a dependency of the header navigation elements with sitestat.com. If it lists in the 3rd party list, try to allow it with the slider.

@@||de.sitestat.com/sueddeutsche/sueddeutsche/*

**Comment by KommX** [comment]
@rvaneijk You're right.

**Comment by cooperq** [comment]
Cool, I will see if we should add sitestat.com to the cookie block list so this won't happen again.

**Comment by rvaneijk** [comment]
I do not recommend to waive sitestat.com with a web-wide exception. Hence, I suggested the site-specific regular expression @@||de.sitestat.com/sueddeutsche/sueddeutsche/*. 

Ideally Privacy Badger should allow this site-specific resource AND block any high-entropy identifier in the request header. Whether the site navigation works without the identifier needs testing. If not, it should be flagged as an edge case that is best left to the user because it is tracking (site wide and perhaps even web wide), but cannot be blocked due to the dependency.

**Comment by KidPluto** [comment]
Not able to reproduce.  This one fixed?  Thanks.

**Comment by deisi** [comment]
for me its blocked and adding `@@||de.sitestat.com/sueddeutsche/sueddeutsche/*` to the list of disabled sites doesn't work. I also see no domain with `sitestat` in the slider list.

**Comment by ghostwords** [comment]
Hi @deisi! The Adblock Plus-style filter expression wouldn't do anything with modern versions of Privacy Badger since Privacy Badger is no longer based on Adblock Plus.

What kind of breakage are you experiencing on `www.sueddeutsche.de`? I see a lot of "disable your ad blocker" reports submitted by users, which would make Süddeutsche Zeitung another example of #1596.

**Comment by ghostwords** [comment]
Looks like reports really picked up in the last month:
```
+---------+----------+
| ym      | count(*) |
+---------+----------+
| 2018-12 |       13 |
| 2018-11 |        3 |
| 2018-09 |        3 |
| 2018-07 |        1 |
| 2018-06 |        3 |
| 2018-05 |        1 |
| 2018-02 |        1 |
| 2017-12 |        5 |
| 2017-11 |        2 |
| 2017-10 |        2 |
| 2017-09 |        3 |
| 2017-08 |        4 |
...
```
Perhaps they activated their adblocker blocking recently.

**Comment by deisi** [comment]
@ghostwords 
Hey, year I think you are right it is  #1596.

**Comment by ghostwords** [comment]
It appears this is no longer an issue as of June 2020.
