### ISSUE TITLE
Please implement Chrome settings sync

### ISSUE THREAD

**Issue by axelcostaspena** [EFForg/privacybadger#645]
So our custom block rules are synced across a single user's several PCs.

https://developer.chrome.com/extensions/storage#property-sync

**Comment by charlesprogrammr** [comment]
It would be useful if settings could be utilized from multiple browsers on the same machine, as well. I have Chrome, Chrome Canary, Whitehat Aviator on my machine, using each for separate tasks (e.g. banking, browsing, etc.) to breakup any tracking by insincere parties. If cookies from one would trip blocking for the others, it would be a very good thing.

**Comment by cooperq** [comment]
So this isn't as easy as it looks on the surface, using the chrome sync api severely limits the amount of data that we can store, right now we are using a bit more data than can be stored with chrome sync, we would have to rethink how we store user data if we wanted to take this approach. 

as for being able to import/export settings see #121

**Comment by ghostwords** [comment]
Unfortunately, [`chrome.storage.sync`](https://github.com/EFForg/privacybadger/issues/1115#issuecomment-336909824) is limited to around 100 KB, which is unlikely to be enough to fit your Badger's learning database.

**Comment by jokeyrhyme** [comment]
Perhaps we can use Google Drive's Application Data for this purpose?
https://developers.google.com/drive/v3/web/appdata

**Comment by ghostwords** [comment]
I think that's for Android apps, while what we have is a Chrome extension.

**Comment by jokeyrhyme** [comment]
@ghostwords there are JavaScript examples, and it's mostly REST APIS, so I think we can use them if we have a button on the settings view that requests access to the user's Drive
https://developers.google.com/drive/v3/web/about-auth
scope = https://www.googleapis.com/auth/drive.appfolder

One possible complication is what happens if you sync data from 2 browser instances at nearly the same time? Is this a common case? Does Google Drive's conflict resolution work in the Application Data folder? But does Chrome Sync offer this sort of functionality anyway?

**Comment by knwpsk** [comment]
(I'm new, so please be gentle or guide me)
Also trying to sync my PB whitelist settings across machines and browsers.
AND... would like to sync PB settings across two different user-instances of Chrome *on the same machine* (work persona and home persona).  

<suggestion here> 
If this is "too hard" to develop using Chrome framework as discussed above, I would like to have a way to sync the settings using Dropbox, or Google Drive Sync, or BTSync, etc.  So, maybe I could turn on an option in PB settings that says, "Each time I make a change, automatically export my settings to a file in a designated directory."  Then I just set up that directory to synchronize.  On the other end, tell PB "Each time I start Chrome, check that directory for a new file and import it."

**Comment by ghostwords** [comment]
Hello! Could you go a bit into why you would like to sync Badger settings automatically?

If one of your Badgers learned different domains from another of your Badgers, that's OK, I don't see a problem. The big idea is to stop continuous tracking of your Web activities. If a tracker sees you twice before your Badger in another browser profile learns to block it, no big deal, I think. There is also manual export and import for extreme situations such as new installations.

If you find yourself customizing the sliders much, this is something we'd like to move away from as we want Privacy Badger to be a set-and-forget extension. (I suggest using the "Disable Privacy Badger for This Site" button instead.)

Now if you'd like to keep your list of websites where Privacy Badger is disabled in sync, that is something we may want to implement sometime. There is a clear use case (it's frustrating to have to "teach" your different Badgers which websites to leave alone over and over), plus the Chrome API should support doing this (as the list of disabled sites will likely fit within API limits).

**Comment by knwpsk** [comment]
Ghostwords -- yes, you got it, I want to sync my list of sites for which PB is "disabled" (that's what I meant by "whitelist" in my comments.
And maybe that's particularly important, because one might guess that -- if we just want to sync that list -- it could be done within the Chrome data size limit.
You're correct again, when you implied that I really don't mess with the sliders much.  I usually just whitelist a site if (a) i trust it, and (b) something is broken by the blockers.

**Comment by ghostwords** [comment]
Closing in favor of #2110.
