### ISSUE TITLE
Installation/repair fails if we enforce hashes

### ISSUE THREAD

**Issue by intchloe** [EFForg/privacybadger#843]
Hello!

chrome://flags/#extension-content-verification -> Enforce strict (hard fail if we can't get hashes)

If you have this setting Privacy Badger won't be able to be installed or repaired.

**Comment by cooperq** [comment]
Interesting! I can definitely verify that this is happening. Do you know where I can find more documentation on this feature so I can figure out what's going on here? This is also true of HTTPS Everywhere, I suspect it has something to do with our release process.

**Comment by cooperq** [comment]
Same issue in HTTPS Everywhere: https://github.com/EFForg/https-everywhere/issues/5874

**Comment by bardiharborow** [comment]
I'm hitting this on 53.0.2785.57 even if I have `extension-content-verification` set to `Bootstrap (get expected hashes, but do not enforce them).

**Comment by rodneytamblyn** [comment]
@cooperq So, in the meantime, new users like me are unable to install right?  Should priority of this ticket be raised to blocker?  Any solution involving disabling chrome://flags/#extension-content-verification -> Enforce strict seems like a bad idea....

**Comment by cowlicks** [comment]
Related to #901

**Comment by cooperq** [comment]
Fixed as of 731b76a80c88d029430540097a5a6e347a081eda
We have a fix for this now which will be in the next release. For now
you can go to chrome://flags and find the setting for 'extension content
verification' and change it from 'enforce strict' to 'enforce'. You then
can uninstall and reinstall the extension and it should be fixed. Once
the fix is released you should be able to change it back.

**Comment by cooperq** [comment]
re-opening this since it is still an issue and we still have a workaround in place. We should figure out the right way to solve this. cc @ghostwords

**Comment by ghostwords** [comment]
This no longer appears to be an issue.
