### ISSUE TITLE
Spoof HTTP referrer string of third-party requests

### ISSUE THREAD

**Issue by semente** [EFForg/privacybadger#855]
Once I can't use uMatrix's "HTTP referrer spoof "option because plugin compatibility issues (see #562), would be great if you add into Privacy Badger an option to spoof the HTTP referrer string of any third-party requests instead just for the tracking domains...

I think the way how uMatrix spoof HTTP referrers protects your privacy and still don't cause any issues in websites that uses this information-at least I didnt' have any issue so far with this setup.

> If this setting is checked, uMatrix will spoof the HTTP referrer information if the domain name of the HTTP referrer is third-party to the domain name of net request.

Thank you.

**Comment by ghostwords** [comment]
We're switching to trimming referrers down to the origin (instead of removing entirely) for cookieblocked requests (#2505). Depending on how that pans out, we may do the same for more (all?) third-party requests in the future.

Spoofing the referrer (to the request domain) does break sites (NASA TV, for example), while providing unclear benefits versus removing referrer entirely, or reducing the amount of information disclosed. Closing for now.
