### ISSUE TITLE
Add buttons which clear Privacy Badger data and/or manual settings

### ISSUE THREAD

**Issue by jgillula** [EFForg/privacybadger#971]
We've had a request for the ability to clear Privacy Badger's data without uninstalling it. I think the right way to do this is to have a big scary confirmation box pop up when this happens that says

"Warning! If you clear Privacy Badger's tracking history, Privacy Badger will not be able to block online trackers until a sufficiently long new history has been built. This means that it may take some time before everything currently being blocked is blocked again. Are you sure you want to reset all tracking protection?"

Also, it would be nice to have a separate button which just allows users to clear all manual settings. That one probably doesn't need a big scary warning.

**Comment by alexristich** [comment]
I'm working on a feature that would allow importing and exporting of Privacy Badger data (#982). Once that's finished, I should be able to implement this one fairly easily. Perhaps better anyway, since we'll be able to suggest users the option of exporting their data first before clearing it entirely, allowing them to restore it if they decide they want it back at some point in the future.

**Comment by alexristich** [comment]
@jgillula @cooperq I took a look into this and wrote up a quick implementation of this feature. Initially it didn't look too tricky, though clearing out the whitelisted sites turned out to be a bit trickier, as did deciding whether settings should also be returned to their defaults.

In talking with @ghostwords during today's dev meeting, we wondered whether it might be simpler to instead include some text at the bottom of the "Manage Data" tab on the Options page explaining how to delete your data by deleting and reinstalling the extension. One of the concerns is adding more code that will have to be maintained. I'm not entirely sure which approach is best, so it might be helpful to know how commonly users ask about how to clear their data - if it's a lot of users, a button is probably better, though if it is a relatively small number, writing up a very brief explanation that can be translated might work better.

**Comment by ghostwords** [comment]
This might be related to Firefox not clearing extension profile data when an extension is uninstalled, making it difficult for Privacy Badger users to start fresh. I opened a Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1350018
